// GENERATED by scripts/generate-abi.mjs from src/sand/abi.schema.json — DO NOT EDIT.
// Strides + field offsets for the packed JS<->WASM snapshots, shared enums, and the ABI version.
#pragma once
#include <cstdint>

static const int ABI_VERSION = 25;

// playerSnapshot: id, active, x, y, vx, vy, w, h, facing, grounded, tool, aimX, aimY, health, inputSeq, alive, jumpReady, animState, animFrame, deathTicks, respawnReady, bowCharge, heldItemKind, jetpackFuel, jetpackActive, shieldHealth, shieldActive
enum PlayerSnapshotField : int {
  PS_ID = 0,
  PS_ACTIVE = 1,
  PS_X = 2,
  PS_Y = 3,
  PS_VX = 4,
  PS_VY = 5,
  PS_W = 6,
  PS_H = 7,
  PS_FACING = 8,
  PS_GROUNDED = 9,
  PS_TOOL = 10,
  PS_AIM_X = 11,
  PS_AIM_Y = 12,
  PS_HEALTH = 13,
  PS_INPUT_SEQ = 14,
  PS_ALIVE = 15,
  PS_JUMP_READY = 16,
  PS_ANIM_STATE = 17,
  PS_ANIM_FRAME = 18,
  PS_DEATH_TICKS = 19,
  PS_RESPAWN_READY = 20,
  PS_BOW_CHARGE = 21,
  PS_HELD_ITEM_KIND = 22,
  PS_JETPACK_FUEL = 23,
  PS_JETPACK_ACTIVE = 24,
  PS_SHIELD_HEALTH = 25,
  PS_SHIELD_ACTIVE = 26,
};
static const int PS_STRIDE = 27;

// itemSnapshot: id, kind, material, count, x, y, life, plantType, itemKind, isTool, toolClass, toolTier
enum ItemSnapshotField : int {
  IS_ID = 0,
  IS_KIND = 1,
  IS_MATERIAL = 2,
  IS_COUNT = 3,
  IS_X = 4,
  IS_Y = 5,
  IS_LIFE = 6,
  IS_PLANT_TYPE = 7,
  IS_ITEM_KIND = 8,
  IS_IS_TOOL = 9,
  IS_TOOL_CLASS = 10,
  IS_TOOL_TIER = 11,
};
static const int IS_STRIDE = 12;

// creatureSnapshot: id, species, x, y, vx, vy, w, h, facing, health, maxHealth, alive, animFrame, attackState, attackProgress, aimX, aimY, spawnProgress, attackPattern
enum CreatureSnapshotField : int {
  CSN_ID = 0,
  CSN_SPECIES = 1,
  CSN_X = 2,
  CSN_Y = 3,
  CSN_VX = 4,
  CSN_VY = 5,
  CSN_W = 6,
  CSN_H = 7,
  CSN_FACING = 8,
  CSN_HEALTH = 9,
  CSN_MAX_HEALTH = 10,
  CSN_ALIVE = 11,
  CSN_ANIM_FRAME = 12,
  CSN_ATTACK_STATE = 13,
  CSN_ATTACK_PROGRESS = 14,
  CSN_AIM_X = 15,
  CSN_AIM_Y = 16,
  CSN_SPAWN_PROGRESS = 17,
  CSN_ATTACK_PATTERN = 18,
};
static const int CSN_STRIDE = 19;

// inventorySlot: material, isTool, toolClass, toolTier, count, plantType, itemKind, selected
enum InventorySlotField : int {
  IVS_MATERIAL = 0,
  IVS_IS_TOOL = 1,
  IVS_TOOL_CLASS = 2,
  IVS_TOOL_TIER = 3,
  IVS_COUNT = 4,
  IVS_PLANT_TYPE = 5,
  IVS_ITEM_KIND = 6,
  IVS_SELECTED = 7,
};
static const int IVS_STRIDE = 8;

// projectileSnapshot: id, owner, x, y, vx, vy, charge, kind, fuse, rotation
enum ProjectileSnapshotField : int {
  PRS_ID = 0,
  PRS_OWNER = 1,
  PRS_X = 2,
  PRS_Y = 3,
  PRS_VX = 4,
  PRS_VY = 5,
  PRS_CHARGE = 6,
  PRS_KIND = 7,
  PRS_FUSE = 8,
  PRS_ROTATION = 9,
};
static const int PRS_STRIDE = 10;

// craftingRecipe: id, outputKind, outputMaterial, outputTier, outputCount, ingredientStart, ingredientCount
enum CraftingRecipeField : int {
  CR_ID = 0,
  CR_OUTPUT_KIND = 1,
  CR_OUTPUT_MATERIAL = 2,
  CR_OUTPUT_TIER = 3,
  CR_OUTPUT_COUNT = 4,
  CR_INGREDIENT_START = 5,
  CR_INGREDIENT_COUNT = 6,
};
static const int CR_STRIDE = 7;

// craftingIngredient: kind, value, count
enum CraftingIngredientField : int {
  CI_KIND = 0,
  CI_VALUE = 1,
  CI_COUNT = 2,
};
static const int CI_STRIDE = 3;

// survivalFootprint: id, width, height, cellCount, anchorX, anchorY
enum SurvivalFootprintField : int {
  FP_ID = 0,
  FP_WIDTH = 1,
  FP_HEIGHT = 2,
  FP_CELL_COUNT = 3,
  FP_ANCHOR_X = 4,
  FP_ANCHOR_Y = 5,
};
static const int FP_STRIDE = 6;

// glPlayerExt: x, y, w, h, facing, own, animState, animFrame, alive, heldItemKind, bowCharge, aimX, aimY, jetpackFuel, jetpackActive, shieldHealth, shieldActive
enum GlPlayerExtField : int {
  GLP_X = 0,
  GLP_Y = 1,
  GLP_W = 2,
  GLP_H = 3,
  GLP_FACING = 4,
  GLP_OWN = 5,
  GLP_ANIM_STATE = 6,
  GLP_ANIM_FRAME = 7,
  GLP_ALIVE = 8,
  GLP_HELD_ITEM_KIND = 9,
  GLP_BOW_CHARGE = 10,
  GLP_AIM_X = 11,
  GLP_AIM_Y = 12,
  GLP_JETPACK_FUEL = 13,
  GLP_JETPACK_ACTIVE = 14,
  GLP_SHIELD_HEALTH = 15,
  GLP_SHIELD_ACTIVE = 16,
};
static const int GLP_STRIDE = 17;

// soundEvent: type, x, y, intensity, material, layer
enum SoundEventField : int {
  SND_TYPE = 0,
  SND_X = 1,
  SND_Y = 2,
  SND_INTENSITY = 3,
  SND_MATERIAL = 4,
  SND_LAYER = 5,
};
static const int SND_STRIDE = 6;

// perfSnapshot: stepMs, actorMs, dirtyChunks, dirtyRows, dirtyCells, componentCount, componentCellCount, crossBondCount, lightMs, fillMs, uploadMs, shiftBuffers, shiftTranslate, shiftRegister, shiftFill, groundingMs, crossLayerGroundingMs, componentIndexMs, assemblyUnionMs, carryMs, bodyMs, sandMs, liquidMs, gasMs, reactMs, tailMs, layersMs, crossMs
enum PerfSnapshotField : int {
  PF_STEP_MS = 0,
  PF_ACTOR_MS = 1,
  PF_DIRTY_CHUNKS = 2,
  PF_DIRTY_ROWS = 3,
  PF_DIRTY_CELLS = 4,
  PF_COMPONENT_COUNT = 5,
  PF_COMPONENT_CELL_COUNT = 6,
  PF_CROSS_BOND_COUNT = 7,
  PF_LIGHT_MS = 8,
  PF_FILL_MS = 9,
  PF_UPLOAD_MS = 10,
  PF_SHIFT_BUFFERS = 11,
  PF_SHIFT_TRANSLATE = 12,
  PF_SHIFT_REGISTER = 13,
  PF_SHIFT_FILL = 14,
  PF_GROUNDING_MS = 15,
  PF_CROSS_LAYER_GROUNDING_MS = 16,
  PF_COMPONENT_INDEX_MS = 17,
  PF_ASSEMBLY_UNION_MS = 18,
  PF_CARRY_MS = 19,
  PF_BODY_MS = 20,
  PF_SAND_MS = 21,
  PF_LIQUID_MS = 22,
  PF_GAS_MS = 23,
  PF_REACT_MS = 24,
  PF_TAIL_MS = 25,
  PF_LAYERS_MS = 26,
  PF_CROSS_MS = 27,
};
static const int PF_STRIDE = 28;

// missionSnapshot: revision, missionId, planetId, phase, objectiveCount, threatLevel, extractionX, extractionY, elapsedTicks, recoveredWeaponMask
enum MissionSnapshotField : int {
  MS_REVISION = 0,
  MS_MISSION_ID = 1,
  MS_PLANET_ID = 2,
  MS_PHASE = 3,
  MS_OBJECTIVE_COUNT = 4,
  MS_THREAT_LEVEL = 5,
  MS_EXTRACTION_X = 6,
  MS_EXTRACTION_Y = 7,
  MS_ELAPSED_TICKS = 8,
  MS_RECOVERED_WEAPON_MASK = 9,
};
static const int MS_STRIDE = 10;

// objectiveSnapshot: id, type, state, current, required, worldX, worldY, targetActorId, flags
enum ObjectiveSnapshotField : int {
  OS_ID = 0,
  OS_TYPE = 1,
  OS_STATE = 2,
  OS_CURRENT = 3,
  OS_REQUIRED = 4,
  OS_WORLD_X = 5,
  OS_WORLD_Y = 6,
  OS_TARGET_ACTOR_ID = 7,
  OS_FLAGS = 8,
};
static const int OS_STRIDE = 9;

enum PlayerInput : int {
  PI_LEFT = 1,
  PI_RIGHT = 2,
  PI_JUMP = 4,
  PI_DOWN = 8,
  PI_PRIMARY = 16,
  PI_SECONDARY = 32,
  PI_RUN = 64,
  PI_JETPACK = 128,
  PI_SHIELD = 256,
};

enum InventoryItemKind : uint8_t {
  IK_MATERIAL = 0,
  IK_MINING_TOOL = 1,
  IK_BOW = 2,
  IK_ARROW = 3,
  IK_BLAST_GUN = 4,
  IK_DYNAMITE_SATCHEL = 5,
  IK_BORE_CANNON = 6,
  IK_ACID_MORTAR = 7,
  IK_CLUSTER_LAUNCHER = 8,
  IK_MINIGUN = 9,
  IK_RESCUE_BEAM = 10,
};

enum ProjectileKind : uint8_t {
  PK_ARROW = 0,
  PK_BLAST_ROUND = 1,
  PK_DYNAMITE = 2,
  PK_ACID_SHELL = 3,
  PK_CLUSTER_BOMB = 4,
  PK_MINIGUN_ROUND = 5,
  PK_BORE_BEAM = 6,
  PK_RESCUE_BEAM = 7,
};

enum CraftIngredientKind : uint8_t {
  CIK_MATERIAL = 0,
  CIK_MATERIAL_FLAG = 1,
};

enum Tool : int {
  T_CUBE = 0,
  T_SAND = 1,
  T_WATER = 2,
  T_STONE = 3,
  T_OIL = 4,
  T_FIRE = 5,
  T_ACID = 6,
  T_LAVA = 7,
  T_ICE = 8,
  T_SEED = 9,
  T_DRIFTWOOD = 10,
  T_ERASER = 11,
};

enum CreativeKind : uint8_t {
  CK_MATERIAL = 0,
  CK_SEED = 1,
  CK_ERASER = 2,
  CK_CUBE = 3,
  CK_CREATURE = 4,
};

enum CreatureSpeciesAbi : int {
  CREATURE_MINNOW = 0,
  CREATURE_PIKE = 1,
  CREATURE_FOX = 2,
  CREATURE_HARE = 3,
  CREATURE_CRAWLER = 4,
  CREATURE_MOLE = 5,
  CREATURE_BIRD = 6,
  CREATURE_DYNAMITEER = 7,
  CREATURE_BORE_SENTINEL = 8,
  CREATURE_CAUSTIC_MORTARMAN = 9,
  CREATURE_CLUSTER_WASP = 10,
  CREATURE_MINIGUNNER = 11,
  CREATURE_SURVEYOR = 12,
  CREATURE_SHIELD_ANCHOR = 13,
  CREATURE_QUARRY_FOREMAN = 14,
  CREATURE_REACTOR_WARDEN = 15,
  CREATURE_REACTOR_CORE = 16,
  CREATURE_IRIS_COMMANDER = 17,
  CREATURE_IRIS_ENGINEER = 18,
};

enum CreatureAttackState : uint8_t {
  CAS_IDLE = 0,
  CAS_CHARGING = 1,
  CAS_FIRING = 2,
};

enum PlanetId : uint8_t {
  PL_EARTH = 0,
  PL_MOON = 1,
  PL_MARS = 2,
  PL_SHIP = 3,
};

enum MissionId : uint8_t {
  MI_NONE = 0,
  MI_GREENFALL_RECOVERY = 1,
  MI_SILENT_QUARRY = 2,
  MI_RED_FURNACE = 3,
};

enum MissionPhase : uint8_t {
  MP_INACTIVE = 0,
  MP_ACTIVE = 1,
  MP_EXTRACTION = 2,
  MP_COMPLETE = 3,
  MP_FAILED = 4,
};

enum ObjectiveKind : uint8_t {
  OK_CLEAR = 0,
  OK_RESCUE = 1,
  OK_ANCHOR = 2,
  OK_BOSS = 3,
  OK_CORE = 4,
  OK_EXTRACT = 5,
};

enum ObjectiveState : uint8_t {
  OS_LOCKED = 0,
  OS_ACTIVE = 1,
  OS_COMPLETE = 2,
  OS_FAILED = 3,
};

enum SoundEventType : uint8_t {
  SE_EXPLOSION = 0,
  SE_FUSE = 1,
  SE_IMPACT = 2,
  SE_JUMP = 3,
  SE_LAND = 4,
  SE_PLACE = 5,
  SE_BREAK = 6,
  SE_PICKUP = 7,
  SE_HURT = 8,
  SE_CREATURE = 9,
  SE_FLUID_FALL = 10,
  SE_POWDER_MOVE = 11,
  SE_SOLID_LAND = 12,
  SE_ACID_DISSOLVE = 13,
  SE_CRAFT = 14,
  SE_BOW = 15,
  SE_ARROW_HIT = 16,
  SE_DEATH = 17,
  SE_RESPAWN = 18,
  SE_BLAST_GUN = 19,
  SE_BORE_CHARGE = 20,
  SE_BORE_FIRE = 21,
  SE_ACID_MORTAR = 22,
  SE_CLUSTER_LAUNCH = 23,
  SE_MINIGUN = 24,
  SE_SHIELD_HIT = 25,
  SE_SHIELD_BREAK = 26,
  SE_SPAWN_BREACH = 27,
  SE_WEAPON_EXPLOSION = 28,
};

static const int INV_HOTBAR = 9;
static const int INV_SLOTS = 36;
