// GENERATED by scripts/generate-abi.mjs from src/sand/abi.schema.json — DO NOT EDIT.
// Strides + field offsets for the packed JS<->WASM snapshots, shared enums, and the ABI version.
#pragma once
#include <cstdint>

static const int ABI_VERSION = 15;

// playerSnapshot: id, active, x, y, vx, vy, w, h, facing, grounded, tool, aimX, aimY, health, inputSeq, alive, jumpReady, animState, animFrame
enum PlayerSnapshotField : int {
  PS_ID = 0,
  PS_ACTIVE = 1,
  PS_X = 2,
  PS_Y = 3,
  PS_VX = 4,
  PS_VY = 5,
  PS_W = 6,
  PS_H = 7,
  PS_FACING = 8,
  PS_GROUNDED = 9,
  PS_TOOL = 10,
  PS_AIM_X = 11,
  PS_AIM_Y = 12,
  PS_HEALTH = 13,
  PS_INPUT_SEQ = 14,
  PS_ALIVE = 15,
  PS_JUMP_READY = 16,
  PS_ANIM_STATE = 17,
  PS_ANIM_FRAME = 18,
};
static const int PS_STRIDE = 19;

// itemSnapshot: id, kind, material, count, x, y, life, plantType
enum ItemSnapshotField : int {
  IS_ID = 0,
  IS_KIND = 1,
  IS_MATERIAL = 2,
  IS_COUNT = 3,
  IS_X = 4,
  IS_Y = 5,
  IS_LIFE = 6,
  IS_PLANT_TYPE = 7,
};
static const int IS_STRIDE = 8;

// creatureSnapshot: id, species, x, y, vx, vy, w, h, facing, health, maxHealth, alive, animFrame
enum CreatureSnapshotField : int {
  CSN_ID = 0,
  CSN_SPECIES = 1,
  CSN_X = 2,
  CSN_Y = 3,
  CSN_VX = 4,
  CSN_VY = 5,
  CSN_W = 6,
  CSN_H = 7,
  CSN_FACING = 8,
  CSN_HEALTH = 9,
  CSN_MAX_HEALTH = 10,
  CSN_ALIVE = 11,
  CSN_ANIM_FRAME = 12,
};
static const int CSN_STRIDE = 13;

// inventorySlot: material, isTool, toolClass, toolTier, count, plantType, selected
enum InventorySlotField : int {
  IVS_MATERIAL = 0,
  IVS_IS_TOOL = 1,
  IVS_TOOL_CLASS = 2,
  IVS_TOOL_TIER = 3,
  IVS_COUNT = 4,
  IVS_PLANT_TYPE = 5,
  IVS_SELECTED = 6,
};
static const int IVS_STRIDE = 7;

// survivalFootprint: id, width, height, cellCount, anchorX, anchorY
enum SurvivalFootprintField : int {
  FP_ID = 0,
  FP_WIDTH = 1,
  FP_HEIGHT = 2,
  FP_CELL_COUNT = 3,
  FP_ANCHOR_X = 4,
  FP_ANCHOR_Y = 5,
};
static const int FP_STRIDE = 6;

// glPlayerExt: x, y, w, h, facing, own, animState, animFrame
enum GlPlayerExtField : int {
  GLP_X = 0,
  GLP_Y = 1,
  GLP_W = 2,
  GLP_H = 3,
  GLP_FACING = 4,
  GLP_OWN = 5,
  GLP_ANIM_STATE = 6,
  GLP_ANIM_FRAME = 7,
};
static const int GLP_STRIDE = 8;

// soundEvent: type, x, y, intensity, material, layer
enum SoundEventField : int {
  SND_TYPE = 0,
  SND_X = 1,
  SND_Y = 2,
  SND_INTENSITY = 3,
  SND_MATERIAL = 4,
  SND_LAYER = 5,
};
static const int SND_STRIDE = 6;

// perfSnapshot: stepMs, actorMs, dirtyChunks, dirtyRows, dirtyCells, componentCount, componentCellCount, crossBondCount, lightMs, fillMs, uploadMs, shiftBuffers, shiftTranslate, shiftRegister, shiftFill, groundingMs, crossLayerGroundingMs, componentIndexMs, assemblyUnionMs, carryMs, bodyMs, sandMs, liquidMs, gasMs, reactMs, tailMs, layersMs, crossMs
enum PerfSnapshotField : int {
  PF_STEP_MS = 0,
  PF_ACTOR_MS = 1,
  PF_DIRTY_CHUNKS = 2,
  PF_DIRTY_ROWS = 3,
  PF_DIRTY_CELLS = 4,
  PF_COMPONENT_COUNT = 5,
  PF_COMPONENT_CELL_COUNT = 6,
  PF_CROSS_BOND_COUNT = 7,
  PF_LIGHT_MS = 8,
  PF_FILL_MS = 9,
  PF_UPLOAD_MS = 10,
  PF_SHIFT_BUFFERS = 11,
  PF_SHIFT_TRANSLATE = 12,
  PF_SHIFT_REGISTER = 13,
  PF_SHIFT_FILL = 14,
  PF_GROUNDING_MS = 15,
  PF_CROSS_LAYER_GROUNDING_MS = 16,
  PF_COMPONENT_INDEX_MS = 17,
  PF_ASSEMBLY_UNION_MS = 18,
  PF_CARRY_MS = 19,
  PF_BODY_MS = 20,
  PF_SAND_MS = 21,
  PF_LIQUID_MS = 22,
  PF_GAS_MS = 23,
  PF_REACT_MS = 24,
  PF_TAIL_MS = 25,
  PF_LAYERS_MS = 26,
  PF_CROSS_MS = 27,
};
static const int PF_STRIDE = 28;

enum PlayerInput : int {
  PI_LEFT = 1,
  PI_RIGHT = 2,
  PI_JUMP = 4,
  PI_DOWN = 8,
  PI_PRIMARY = 16,
  PI_SECONDARY = 32,
  PI_RUN = 64,
};

enum Tool : int {
  T_CUBE = 0,
  T_SAND = 1,
  T_WATER = 2,
  T_STONE = 3,
  T_OIL = 4,
  T_FIRE = 5,
  T_ACID = 6,
  T_LAVA = 7,
  T_ICE = 8,
  T_SEED = 9,
  T_DRIFTWOOD = 10,
  T_ERASER = 11,
};

enum CreativeKind : uint8_t {
  CK_MATERIAL = 0,
  CK_SEED = 1,
  CK_ERASER = 2,
  CK_CUBE = 3,
  CK_CREATURE = 4,
};

enum CreatureSpeciesAbi : int {
  CREATURE_MINNOW = 0,
  CREATURE_PIKE = 1,
  CREATURE_FOX = 2,
  CREATURE_HARE = 3,
  CREATURE_CRAWLER = 4,
  CREATURE_MOLE = 5,
  CREATURE_BIRD = 6,
};

enum SoundEventType : uint8_t {
  SE_EXPLOSION = 0,
  SE_FUSE = 1,
  SE_IMPACT = 2,
  SE_JUMP = 3,
  SE_LAND = 4,
  SE_PLACE = 5,
  SE_BREAK = 6,
  SE_PICKUP = 7,
  SE_HURT = 8,
  SE_CREATURE = 9,
  SE_FLUID_FALL = 10,
  SE_POWDER_MOVE = 11,
  SE_SOLID_LAND = 12,
  SE_ACID_DISSOLVE = 13,
};

static const int INV_HOTBAR = 9;
static const int INV_SLOTS = 36;
