// Generated by scripts/generate-biomes.mjs from src/sand/biomes.schema.json.
// Do not edit by hand.
#pragma once

inline constexpr int SURFACE_REGION_WIDTH = 768;
inline constexpr int SURFACE_REGION_JITTER = 96;

enum SurfaceBiomeSelectionMode : uint8_t {
  SBSE_CLIMATE = 0,
  SBSE_REGIONAL = 1,
};

enum CaveBiomeSelectionMode : uint8_t {
  CBSE_BLENDED_DEPTH_BANDS = 0,
  CBSE_ABSOLUTE_DEPTH_BANDS = 1,
  CBSE_FALLBACK = 2,
};

struct BiomeGenerationProfileSelection {
  SurfaceBiomeSelectionMode surfaceMode;
  CaveBiomeSelectionMode caveMode;
  bool requiresOffworldMaterialProfile;
};

static_assert(PLANET_GENERATION_PROFILE_COUNT == 4
              && PLANET_GENERATION_PROFILE_COUNT <= 32,
              "Biome generation profiles must stay exhaustive and mask-safe");
inline constexpr std::array<BiomeGenerationProfileSelection,
                            PLANET_GENERATION_PROFILE_COUNT>
    BIOME_GENERATION_PROFILE_SELECTION = {{
  {SBSE_CLIMATE, CBSE_BLENDED_DEPTH_BANDS, false},
  {SBSE_REGIONAL, CBSE_ABSOLUTE_DEPTH_BANDS, true},
  {SBSE_REGIONAL, CBSE_ABSOLUTE_DEPTH_BANDS, true},
  {SBSE_REGIONAL, CBSE_FALLBACK, false},
}};

inline const BiomeGenerationProfileSelection& biomeGenerationProfileSelection(
    PlanetGenerationProfile profile) {
  if ((unsigned)profile < BIOME_GENERATION_PROFILE_SELECTION.size())
    return BIOME_GENERATION_PROFILE_SELECTION[(size_t)profile];
  assert(false && "invalid planet generation profile");
  return BIOME_GENERATION_PROFILE_SELECTION[(size_t)PGP_EARTH];
}

enum SurfaceClimateVariable : uint8_t {
  SCV_TEMPERATURE = 0,
  SCV_MOISTURE = 1,
  SCV_ALTITUDE = 2,
  SCV_RUGGED = 3,
  SCV_SURFACE_MINUS_SEA = 4,
  SCV_ANOMALY = 5,
  SCV_COUNT = 6,
};

enum SurfaceClimateComparison : uint8_t {
  SCC_LESS_THAN = 0,
  SCC_GREATER_THAN = 1,
};

enum CaveBiomeProfile : uint8_t {
  CBP_DEFAULT = 0,
  CBP_CRYSTAL = 1,
  CBP_MUSHROOM = 2,
  CBP_LUSH = 3,
  CBP_DEEP_MAGMA = 4,
  CBP_DEEP_GEODE = 5,
  CBP_DEEP_FOSSIL = 6,
  CBP_DEEP_VOID = 7,
  CBP_COUNT = 8,
};

enum CaveUpperDressingHandler : uint8_t {
  CUDH_NONE = 0,
  CUDH_DEFAULT = 1,
  CUDH_CRYSTAL = 2,
  CUDH_MUSHROOM = 3,
  CUDH_LUSH = 4,
  CUDH_COUNT = 5,
};

enum CaveDeepDressingHandler : uint8_t {
  CDDH_NONE = 0,
  CDDH_MAGMA = 1,
  CDDH_GEODE = 2,
  CDDH_FOSSIL = 3,
  CDDH_VOID = 4,
  CDDH_COUNT = 5,
};

enum CaveDeepStructureHandler : uint8_t {
  CDSH_NONE = 0,
  CDSH_MAGMA = 1,
  CDSH_GEODE = 2,
  CDSH_FOSSIL = 3,
  CDSH_VOID = 4,
  CDSH_COUNT = 5,
};

enum CaveDeepFloorPolicy : uint8_t {
  CDFP_SEARCH = 0,
  CDFP_MAGMA_LAKE = 1,
  CDFP_COUNT = 2,
};

struct OffworldBiomeDef {
  uint8_t surfaceFlat, surfaceSteep, shallow, crust;
  uint8_t shallowOverride, shallowPocket, deepPocket;
  uint8_t formation, formationAccent, foundation;
  int overrideDepth, deepPocketMinDepth;
  double shallowPocketCut, deepPocketCut;
  bool shallowPocketAbove, deepPocketAbove;
};

struct SurfaceClimateTerm {
  SurfaceClimateVariable variable;
  SurfaceClimateComparison comparison;
  double threshold;
};

struct SurfaceClimateClause {
  uint16_t termOffset;
  uint8_t termCount;
};

enum SurfaceStructureStyle : uint8_t {
  SSS_VILLAGE = 0,
  SSS_OBSERVATORY = 1,
};

enum SurfaceFormationStyle : uint8_t {
  SFS_BOULDER = 0,
  SFS_STACK = 1,
  SFS_SPIRE = 2,
  SFS_FOSSIL = 3,
};

struct SurfaceBiomeDef {
  Biome id;
  const char* name;
  int selectionPriority;
  uint16_t climateClauseOffset;
  uint8_t climateClauseCount;
  double surfaceReliefScale, surfaceDetailAmplitude, surfaceRidgeMix, surfaceOffset;
  double surfaceDetailFrequency;
  SurfaceFormationStyle formationStyle;
  uint8_t formationMaterial, formationAccent;
  double formationChance;
  int formationHeight;
  int soilScale, soilAdd;
  uint8_t flatSkin, steepSkin, soilTop, soilBase;
  int soilBaseNumerator, soilBaseDenominator;
  double treeProbabilityScale;
  uint8_t treeFirst, treeSecond, treeThird;
  double treeFirstCut, treeSecondCut;
  SurfaceStructureStyle structureStyle;
  uint8_t structureWall, structureFoundation;
  bool copperRich;
  bool allowsSurfaceStructures;
};

inline constexpr std::array<SurfaceClimateTerm, 18>
    SURFACE_CLIMATE_TERMS = {{
  {SCV_MOISTURE, SCC_GREATER_THAN, 0.51},
  {SCV_MOISTURE, SCC_LESS_THAN, 0.42},
  {SCV_TEMPERATURE, SCC_GREATER_THAN, 0.4},
  {SCV_ALTITUDE, SCC_GREATER_THAN, 0.28},
  {SCV_RUGGED, SCC_GREATER_THAN, 0.58},
  {SCV_ALTITUDE, SCC_GREATER_THAN, 0.52},
  {SCV_TEMPERATURE, SCC_GREATER_THAN, 0.27},
  {SCV_TEMPERATURE, SCC_LESS_THAN, 0.29},
  {SCV_ALTITUDE, SCC_GREATER_THAN, 0.34},
  {SCV_TEMPERATURE, SCC_LESS_THAN, 0.45},
  {SCV_TEMPERATURE, SCC_GREATER_THAN, 0.5},
  {SCV_MOISTURE, SCC_GREATER_THAN, 0.55},
  {SCV_MOISTURE, SCC_GREATER_THAN, 0.62},
  {SCV_SURFACE_MINUS_SEA, SCC_GREATER_THAN, -20},
  {SCV_TEMPERATURE, SCC_GREATER_THAN, 0.38},
  {SCV_ANOMALY, SCC_GREATER_THAN, 0.64},
  {SCV_SURFACE_MINUS_SEA, SCC_LESS_THAN, -8},
  {SCV_ALTITUDE, SCC_LESS_THAN, 0.4},
}};

inline constexpr std::array<SurfaceClimateClause, 10>
    SURFACE_CLIMATE_CLAUSES = {{
  {0, 0},
  {0, 1},
  {1, 2},
  {3, 2},
  {5, 2},
  {7, 1},
  {8, 2},
  {10, 2},
  {12, 3},
  {15, 3},
}};

inline constexpr std::array<SurfaceBiomeDef, SURFACE_BIOME_COUNT> SURFACE_BIOMES = {{
  {BIOME_PLAINS, "plains", 6, 0, 1,
   0.38, 4, 0, -10, 0.0045,
   SFS_BOULDER, STONE, MOSS, 0.18, 6,
   1, 2, GRASS, SAND, DIRT, DIRT,
   0, 1, 0.45,
   PT_BUSH, PT_OAK, PT_OAK, 0.75, 1,
   SSS_VILLAGE, BRICK, BRICK, false, true},
  {BIOME_FOREST, "forest", 5, 1, 1,
   0.72, 8, 0.15, -12, 0.0065,
   SFS_BOULDER, STONE, MOSS, 0.32, 8,
   1, 2, GRASS, SAND, DIRT, DIRT,
   0, 1, 3.8,
   PT_PINE, PT_OAK, PT_OAK, 0.85, 1,
   SSS_VILLAGE, STONE, STONE, false, true},
  {BIOME_DESERT, "desert", 2, 2, 1,
   0.2, 22, 0, -22, 0.0032,
   SFS_STACK, SANDSTONE, CLAY, 0.42, 18,
   4, 0, SAND, SAND, SAND, SANDSTONE,
   2, 3, 0.8,
   PT_CACTUS, PT_CACTUS, PT_CACTUS, 1, 1,
   SSS_VILLAGE, SANDSTONE, SANDSTONE, true, true},
  {BIOME_ROCKY, "bone highlands", 0, 3, 2,
   1.25, 25, 0.95, -35, 0.007,
   SFS_FOSSIL, BONE, PALESTONE, 1, 25,
   0, 6, BONE, PALESTONE, PALESTONE, DEEPSTONE,
   2, 3, 0,
   PT_OAK, PT_OAK, PT_OAK, 1, 1,
   SSS_VILLAGE, BRICK, BRICK, false, false},
  {BIOME_TUNDRA, "tundra", 1, 5, 2,
   0.62, 9, 0.1, -14, 0.004,
   SFS_BOULDER, STONE, ICE, 0.4, 10,
   1, 4, SNOW, SNOW, SNOW, DIRT,
   1, 2, 0.65,
   PT_PINE, PT_PINE, PT_PINE, 1, 1,
   SSS_VILLAGE, STONE, STONE, false, true},
  {BIOME_JUNGLE, "jungle", 4, 7, 1,
   0.62, 10, 0.1, -15, 0.006,
   SFS_BOULDER, STONE, MOSS, 0.32, 11,
   1, 3, GRASS, SAND, DIRT, DIRT,
   0, 1, 5.2,
   PT_BUSH, PT_OAK, PT_OAK, 0.15, 1,
   SSS_VILLAGE, CLAY, STONE, true, true},
  {BIOME_SWAMP, "swamp", 3, 8, 1,
   0.07, 12, 0, -1, 0.007,
   SFS_BOULDER, STONE, MOSS, 0.15, 5,
   2, 2, MUD, MUD, MUD, MUD,
   0, 1, 2,
   PT_WILLOW, PT_OAK, PT_BUSH, 0.85, 0.95,
   SSS_VILLAGE, STONE, STONE, false, true},
  {BIOME_WATCHWOOD, "watchwood", -1, 9, 1,
   0.34, 13, 0, -18, 0.005,
   SFS_SPIRE, PALESTONE, EYE_WOOD, 0.48, 20,
   2, 4, VEIN_SOIL, PALESTONE, VEIN_SOIL, PALESTONE,
   1, 2, 1,
   PT_EYE, PT_EYE, PT_EYE, 1, 1,
   SSS_OBSERVATORY, PALESTONE, PALESTONE, false, true},
}};

static_assert(OFFWORLD_MATERIAL_PROFILE_COUNT == 3,
              "Biome and ABI offworld material profiles must stay exhaustive");
inline constexpr std::array<std::array<OffworldBiomeDef, SURFACE_BIOME_COUNT>,
                            OFFWORLD_MATERIAL_PROFILE_COUNT> OFFWORLD_BIOME_PROFILES = {{
  {{
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  }},
  {{
    {SALT, DEBRIS, DEBRIS, STONE, EMPTY, EMPTY, EMPTY, DEBRIS, DEBRIS, CLAY, 0, 0, 0, 0, true, true},
    {CRYSTAL, CRYSTAL, DEBRIS, STONE, EMPTY, EMPTY, EMPTY, CRYSTAL, LIGHT, CLAY, 0, 0, 0, 0, true, true},
    {SALT, DEBRIS, SALT, STONE, EMPTY, EMPTY, EMPTY, DEBRIS, DEBRIS, CLAY, 0, 0, 0, 0, true, true},
    {SALT, DEBRIS, DEBRIS, STONE, EMPTY, EMPTY, EMPTY, DEEPSTONE, DEEPSTONE, CLAY, 0, 0, 0, 0, true, true},
    {SNOW, SNOW, DEBRIS, STONE, ICE, EMPTY, EMPTY, ICE, ICE, CLAY, 4, 0, 0, 0, true, true},
    {MYCELIUM, MYCELIUM, DEBRIS, STONE, EMPTY, MYCELIUM, EMPTY, MYCELIUM, MYCELIUM, CLAY, 0, 0, 0.72, 0, true, true},
    {SALT, SALT, DEBRIS, STONE, EMPTY, EMPTY, BRINE, STONE, STONE, CLAY, 0, 24, 0, 0.012, true, false},
    {SALT, DEBRIS, DEBRIS, STONE, EMPTY, EMPTY, EMPTY, DEBRIS, DEBRIS, CLAY, 0, 0, 0, 0, true, true}
  }},
  {{
    {SAND, CLAY, CLAY, SANDSTONE, EMPTY, EMPTY, EMPTY, BRICK, BRICK, CLAY, 0, 0, 0, 0, true, true},
    {SAND, CLAY, CLAY, SANDSTONE, EMPTY, EMPTY, EMPTY, BRICK, BRICK, CLAY, 0, 0, 0, 0, true, true},
    {SAND, CLAY, CLAY, SANDSTONE, EMPTY, EMPTY, EMPTY, SANDSTONE, SANDSTONE, SANDSTONE, 0, 0, 0, 0, true, true},
    {DEBRIS, DEBRIS, CLAY, STONE, EMPTY, EMPTY, EMPTY, DEEPSTONE, DEEPSTONE, CLAY, 0, 0, 0, 0, true, true},
    {SNOW, SNOW, CLAY, SANDSTONE, ICE, EMPTY, EMPTY, ICE, ICE, CLAY, 3, 0, 0, 0, true, true},
    {GRASS, GRASS, CLAY, SANDSTONE, EMPTY, DIRT, MYCELIUM, MYCELIUM, MYCELIUM, CLAY, 0, 28, 0.42, 0.985, true, true},
    {SALT, SALT, CLAY, SANDSTONE, EMPTY, EMPTY, ACID, CLAY, CLAY, CLAY, 0, 30, 0, 0.014, true, false},
    {SAND, CLAY, CLAY, SANDSTONE, EMPTY, EMPTY, EMPTY, BRICK, BRICK, CLAY, 0, 0, 0, 0, true, true}
  }}
}};

inline constexpr std::array<Biome, 8> SURFACE_BIOME_SELECTION_ORDER = {{
  BIOME_WATCHWOOD, BIOME_ROCKY, BIOME_TUNDRA, BIOME_DESERT, BIOME_SWAMP, BIOME_JUNGLE, BIOME_FOREST, BIOME_PLAINS
}};
inline constexpr Biome SURFACE_BIOME_FALLBACK = BIOME_PLAINS;

struct BiomeSelectionRange {
  uint16_t offset;
  uint8_t count;
};

inline constexpr std::array<Biome, 13>
    REGIONAL_SURFACE_BIOME_SELECTION = {{
  BIOME_TUNDRA, BIOME_DESERT, BIOME_ROCKY, BIOME_FOREST, BIOME_SWAMP, BIOME_JUNGLE, BIOME_TUNDRA, BIOME_ROCKY, BIOME_DESERT, BIOME_PLAINS, BIOME_SWAMP, BIOME_JUNGLE, BIOME_ROCKY
}};
inline constexpr std::array<BiomeSelectionRange, PLANET_GENERATION_PROFILE_COUNT>
    REGIONAL_SURFACE_BIOME_PROFILE_POOLS = {{
  {0, 0},
  {0, 6},
  {6, 6},
  {12, 1},
}};

inline Biome selectRegionalSurfaceBiome(PlanetGenerationProfile profile,
                                        double pick) {
  if ((unsigned)profile >= REGIONAL_SURFACE_BIOME_PROFILE_POOLS.size()) {
    assert(false && "invalid regional surface biome profile");
    return SURFACE_BIOME_FALLBACK;
  }
  const BiomeSelectionRange& pool =
    REGIONAL_SURFACE_BIOME_PROFILE_POOLS[(size_t)profile];
  if (pool.count == 0) {
    assert(false && "surface biome profile has no regional selection pool");
    return SURFACE_BIOME_FALLBACK;
  }
  int index = (int)(pick * pool.count);
  if (index < 0) index = 0;
  if (index >= pool.count) index = pool.count - 1;
  return REGIONAL_SURFACE_BIOME_SELECTION[(size_t)pool.offset + (size_t)index];
}

struct CaveBiomeDef {
  CaveBiome id;
  const char* name;
  CaveBiomeProfile profile;
  bool deep;
  double lavaHazard, methaneHazard;
  uint8_t wallAccent;
  double wallAccentCut, crystalCut;
  uint8_t wallTendrilMaterial;
  double wallTendrilDetailCut, wallTendrilNoiseCut;
  uint8_t embeddedVeinMaterial;
  double embeddedVeinCut;
  uint8_t monumentWall, monumentAccent;
};

inline constexpr std::array<CaveBiomeDef, CAVE_BIOME_COUNT> CAVE_BIOMES = {{
  {CAVE_DEFAULT, "default", CBP_DEFAULT, false,
   0.01, 0.006, EMPTY,
   2, 0.966, EMPTY,
   2, 0,
   EMPTY, 2,
   BRICK, CRYSTAL},
  {CAVE_CRYSTAL, "crystal", CBP_CRYSTAL, false,
   0.0012, 0.001, EMPTY,
   2, 0.955, EMPTY,
   2, 0,
   EMPTY, 2,
   BRICK, CRYSTAL},
  {CAVE_MUSHROOM, "mushroom", CBP_MUSHROOM, false,
   0.0034, 0.009, MYCELIUM,
   0.96, 0.966, MYCELIUM,
   0.62, 0.024,
   MYCELIUM, 0.86,
   BRICK, GLOWSHROOM},
  {CAVE_LUSH, "lush", CBP_LUSH, false,
   0.0034, 0.002, MOSS,
   0.55, 0.966, EMPTY,
   2, 0,
   EMPTY, 2,
   BRICK, MOSS},
  {CAVE_DEEP_MAGMA, "deep magma", CBP_DEEP_MAGMA, true,
   0.0034, 0.001, GOLD_ORE,
   0.965, 0.966, EMPTY,
   2, 0,
   EMPTY, 2,
   BRICK, LAVA},
  {CAVE_DEEP_GEODE, "deep geode", CBP_DEEP_GEODE, true,
   0.0034, 0.001, CRYSTAL,
   0.925, 0.966, EMPTY,
   2, 0,
   EMPTY, 2,
   BRICK, CRYSTAL},
  {CAVE_DEEP_FOSSIL, "deep fossil", CBP_DEEP_FOSSIL, true,
   0.0034, 0.001, SANDSTONE,
   0.94, 0.966, EMPTY,
   2, 0,
   EMPTY, 2,
   SANDSTONE, DEBRIS},
  {CAVE_DEEP_VOID, "deep void", CBP_DEEP_VOID, true,
   0.0034, 0.001, MYCELIUM,
   0.955, 0.966, EMPTY,
   2, 0,
   EMPTY, 2,
   BRICK, GLOWSHROOM},
}};

struct CaveBiomeSelectionSegment {
  CaveBiome biome;
  double cut;
};

inline constexpr std::array<CaveBiomeSelectionSegment,
                            12>
    SHALLOW_CAVE_BIOME_PROFILE_SEGMENTS = {{
  {CAVE_DEFAULT, 0.1},
  {CAVE_CRYSTAL, 0.4},
  {CAVE_MUSHROOM, 0.7},
  {CAVE_LUSH, 1},
  {CAVE_DEFAULT, 0.25},
  {CAVE_CRYSTAL, 0.5},
  {CAVE_MUSHROOM, 0.73},
  {CAVE_LUSH, 1},
  {CAVE_DEFAULT, 0.25},
  {CAVE_CRYSTAL, 0.5},
  {CAVE_MUSHROOM, 0.73},
  {CAVE_LUSH, 1},
}};
inline constexpr std::array<CaveBiomeSelectionSegment,
                            12>
    DEEP_CAVE_BIOME_PROFILE_SEGMENTS = {{
  {CAVE_DEEP_MAGMA, 0.42},
  {CAVE_DEEP_GEODE, 0.5},
  {CAVE_DEEP_FOSSIL, 0.58},
  {CAVE_DEEP_VOID, 1},
  {CAVE_DEEP_GEODE, 0.34},
  {CAVE_DEEP_FOSSIL, 0.58},
  {CAVE_DEEP_VOID, 0.78},
  {CAVE_DEEP_GEODE, 1},
  {CAVE_DEEP_MAGMA, 0.34},
  {CAVE_DEEP_FOSSIL, 0.58},
  {CAVE_DEEP_VOID, 0.78},
  {CAVE_DEEP_GEODE, 1},
}};
inline constexpr std::array<BiomeSelectionRange, PLANET_GENERATION_PROFILE_COUNT>
    SHALLOW_CAVE_BIOME_PROFILE_POOLS = {{
  {0, 4},
  {4, 4},
  {8, 4},
  {12, 0},
}};
inline constexpr std::array<BiomeSelectionRange, PLANET_GENERATION_PROFILE_COUNT>
    DEEP_CAVE_BIOME_PROFILE_POOLS = {{
  {0, 4},
  {4, 4},
  {8, 4},
  {12, 0},
}};

inline constexpr std::array<CaveBiome, 4> SHALLOW_CAVE_BIOME_SELECTION_ORDER = {{
  CAVE_DEFAULT, CAVE_CRYSTAL, CAVE_MUSHROOM, CAVE_LUSH
}};
inline constexpr std::array<CaveBiome, 4> DEEP_CAVE_BIOME_SELECTION_ORDER = {{
  CAVE_DEEP_MAGMA, CAVE_DEEP_GEODE, CAVE_DEEP_FOSSIL, CAVE_DEEP_VOID
}};
inline constexpr CaveBiome CAVE_BIOME_FALLBACK = CAVE_DEFAULT;

constexpr bool surfaceBiomeTableIsComplete() {
  for (int i = 0; i < SURFACE_BIOME_COUNT; i++)
    if ((int)SURFACE_BIOMES[i].id != i
        || (size_t)SURFACE_BIOMES[i].climateClauseOffset
             + SURFACE_BIOMES[i].climateClauseCount
           > SURFACE_CLIMATE_CLAUSES.size()) return false;
  return true;
}
constexpr bool caveBiomeTableIsComplete() {
  for (int i = 0; i < CAVE_BIOME_COUNT; i++)
    if ((int)CAVE_BIOMES[i].id != i) return false;
  return true;
}
static_assert(SURFACE_BIOME_COUNT <= 32 && surfaceBiomeTableIsComplete(),
              "Surface biome descriptors must be dense and exhaustive");
static_assert(CAVE_BIOME_COUNT <= 32 && caveBiomeTableIsComplete(),
              "Cave biome descriptors must be dense and exhaustive");

inline bool surfaceBiomeClimateMatches(
    const SurfaceBiomeDef& biome, double temperature, double moisture,
    double altitude, double rugged, double surfaceMinusSea, double anomaly) {
  const std::array<double, SCV_COUNT> values = {{
    temperature, moisture, altitude, rugged, surfaceMinusSea, anomaly,
  }};
  for (uint16_t clauseIndex = 0; clauseIndex < biome.climateClauseCount;
       clauseIndex++) {
    const SurfaceClimateClause& clause = SURFACE_CLIMATE_CLAUSES[
      (size_t)biome.climateClauseOffset + clauseIndex];
    bool matches = true;
    for (uint16_t termIndex = 0; termIndex < clause.termCount; termIndex++) {
      const SurfaceClimateTerm& term = SURFACE_CLIMATE_TERMS[
        (size_t)clause.termOffset + termIndex];
      double value = values[(size_t)term.variable];
      bool termMatches = term.comparison == SCC_LESS_THAN
        ? value < term.threshold : value > term.threshold;
      if (!termMatches) { matches = false; break; }
    }
    if (matches) return true;
  }
  return false;
}

inline CaveBiome selectCaveBiome(PlanetGenerationProfile profile,
                                 bool deep, double pick) {
  const BiomeGenerationProfileSelection& selection =
    biomeGenerationProfileSelection(profile);
  if (selection.caveMode == CBSE_FALLBACK) return CAVE_BIOME_FALLBACK;
  const CaveBiomeSelectionSegment* segments = deep
    ? DEEP_CAVE_BIOME_PROFILE_SEGMENTS.data()
    : SHALLOW_CAVE_BIOME_PROFILE_SEGMENTS.data();
  const auto& pools = deep ? DEEP_CAVE_BIOME_PROFILE_POOLS
                           : SHALLOW_CAVE_BIOME_PROFILE_POOLS;
  const BiomeSelectionRange& pool = pools[(size_t)profile];
  if (pool.count == 0) {
    assert(false && "cave biome profile has no selection pool");
    return CAVE_BIOME_FALLBACK;
  }
  for (uint16_t index = 0; index < pool.count; index++) {
    const CaveBiomeSelectionSegment& segment =
      segments[(size_t)pool.offset + index];
    if (pick < segment.cut || index + 1 == pool.count) return segment.biome;
  }
  __builtin_unreachable();
}

inline const SurfaceBiomeDef& surfaceBiomeDef(int biome) {
  if ((unsigned)biome < SURFACE_BIOMES.size()) return SURFACE_BIOMES[(size_t)biome];
  assert(false && "invalid surface biome id");
  return SURFACE_BIOMES[(size_t)SURFACE_BIOME_FALLBACK];
}
inline const OffworldBiomeDef& offworldBiomeDef(OffworldMaterialProfile profile,
                                                int biome) {
  if ((unsigned)profile < OFFWORLD_BIOME_PROFILES.size()
      && profile != OWMP_NONE
      && (unsigned)biome < SURFACE_BIOME_COUNT)
    return OFFWORLD_BIOME_PROFILES[(size_t)profile][(size_t)biome];
  assert(false && "invalid offworld biome material profile or biome id");
  return OFFWORLD_BIOME_PROFILES[(size_t)OWMP_LUNAR][(size_t)SURFACE_BIOME_FALLBACK];
}
inline const CaveBiomeDef& caveBiomeDef(int biome) {
  if ((unsigned)biome < CAVE_BIOMES.size()) return CAVE_BIOMES[(size_t)biome];
  assert(false && "invalid cave biome id");
  return CAVE_BIOMES[(size_t)CAVE_BIOME_FALLBACK];
}
