// GENERATED by scripts/generate-abi.mjs — DO NOT EDIT.
// Creature ids, simulation/population descriptors, render metadata, and exhaustive behavior policies.
#pragma once

enum CreatureSpeciesId : uint8_t {
  CS_MINNOW = CREATURE_MINNOW,
  CS_PIKE = CREATURE_PIKE,
  CS_FOX = CREATURE_FOX,
  CS_HARE = CREATURE_HARE,
  CS_CRAWLER = CREATURE_CRAWLER,
  CS_MOLE = CREATURE_MOLE,
  CS_BIRD = CREATURE_BIRD,
  CS_BRIAR_GOBLIN = CREATURE_BRIAR_GOBLIN,
  CS_FEN_WITCH = CREATURE_FEN_WITCH,
  CS_OATHLESS_ARCHER = CREATURE_OATHLESS_ARCHER,
  CS_VILLAGER_SCHOLAR = CREATURE_VILLAGER_SCHOLAR,
  CS_STONE_GUARDIAN = CREATURE_STONE_GUARDIAN,
  CS_VILLAGER_KEEPER = CREATURE_VILLAGER_KEEPER,
  CS_VILLAGER_SMITH = CREATURE_VILLAGER_SMITH,
  CS_VILLAGER = CREATURE_VILLAGER,
  CS_THORNBOUND_HART = CREATURE_THORNBOUND_HART,
  CS_MIRE_MATRON = CREATURE_MIRE_MATRON,
  CS_CINDER_CASTELLAN = CREATURE_CINDER_CASTELLAN,
  CS_HOLLOW_BELLKEEPER = CREATURE_HOLLOW_BELLKEEPER,
  CS_BRIAR_WOLF = CREATURE_BRIAR_WOLF,
  CS_BELL_BAT = CREATURE_BELL_BAT,
  CS_BONE_GUARD = CREATURE_BONE_GUARD,
  CS_FEN_WISP = CREATURE_FEN_WISP,
  CS_ROOT_KNIGHT = CREATURE_ROOT_KNIGHT,
  CS_FROST_GIANT = CREATURE_FROST_GIANT,
  CS_MUMMY = CREATURE_MUMMY,
  CS_LAVA_TOAD = CREATURE_LAVA_TOAD,
  CS_VILLAGE_GUARD = CREATURE_VILLAGE_GUARD,
  CS_VILLAGE_HUNTER = CREATURE_VILLAGE_HUNTER,
  CS_CINDERJAW_DRAGON = CREATURE_CINDERJAW_DRAGON,
  CS_COUNT = 30,
};

enum CreaturePopulationProfile : uint8_t { CPOP_AMBIENT = 0, CPOP_ENCOUNTER, CPOP_SCRIPTED, CPOP_COUNT };
enum CreatureProtection : uint8_t { CPROT_NONE = 0, CPROT_ALWAYS, CPROT_PROTECTED_CREW, CPROT_COUNT };

enum CreatureBehaviorProfile : uint8_t {
  CRBH_GENERIC = 0,
  CRBH_RANGED = 1,
  CRBH_HOVER = 2,
  CRBH_COUNT = 3,
};

enum CreatureRenderProfile : uint8_t {
  CRP_MINNOW = 0,
  CRP_PIKE = 1,
  CRP_FOX = 2,
  CRP_HARE = 3,
  CRP_CRAWLER = 4,
  CRP_MOLE = 5,
  CRP_BIRD = 6,
  CRP_BRIAR_GOBLIN = 7,
  CRP_FEN_WITCH = 8,
  CRP_BELL_BAT = 9,
  CRP_OATHLESS_ARCHER = 10,
  CRP_VILLAGER_SCHOLAR = 11,
  CRP_STONE_GUARDIAN = 12,
  CRP_VILLAGER_KEEPER = 13,
  CRP_VILLAGER_SMITH = 14,
  CRP_VILLAGER = 15,
  CRP_FROST_GIANT = 16,
  CRP_MUMMY = 17,
  CRP_LAVA_TOAD = 18,
  CRP_VILLAGE_GUARD = 19,
  CRP_VILLAGE_HUNTER = 20,
  CRP_CINDERJAW_DRAGON = 21,
  CRP_COUNT = 22,
};

enum CreatureRenderAsset : uint8_t {
  CRA_MINNOW = 0,
  CRA_PIKE = 1,
  CRA_FOX = 2,
  CRA_HARE = 3,
  CRA_CRAWLER = 4,
  CRA_MOLE = 5,
  CRA_BIRD = 6,
  CRA_BRIAR_GOBLIN = 7,
  CRA_FEN_WITCH = 8,
  CRA_BELL_BAT = 9,
  CRA_OATHLESS_ARCHER = 10,
  CRA_VILLAGER_SCHOLAR = 11,
  CRA_STONE_GUARDIAN = 12,
  CRA_VILLAGER_KEEPER = 13,
  CRA_VILLAGER_SMITH = 14,
  CRA_VILLAGER = 15,
  CRA_FROST_GIANT = 16,
  CRA_MUMMY = 17,
  CRA_LAVA_TOAD = 18,
  CRA_VILLAGE_GUARD = 19,
  CRA_VILLAGE_HUNTER = 20,
  CRA_CINDERJAW_DRAGON = 21,
  CRA_COUNT = 22,
};

enum CreatureAttackHandler : uint8_t {
  CAH_GENERIC = 0,
  CAH_COUNT = 1,
};
enum CreatureTelegraphHandler : uint8_t {
  CTH_NONE = 0,
  CTH_COUNT = 1,
};
enum CreatureFlyingMovement : uint8_t {
  CFM_DEFAULT = 0,
  CFM_HOVER = 1,
  CFM_COUNT = 2,
};
enum CreatureWeaponOverlay : uint8_t {
  CWO_NONE = 0,
  CWO_COUNT = 1,
};

struct CreatureBehaviorProfileDef {
  CreatureBehaviorProfile id;
  CreatureAttackHandler attack;
  CreatureTelegraphHandler telegraph;
  InventoryItemKind dropItem;
  CreatureFlyingMovement flyingMovement;
  int nearRange, farRange;
  CreatureWeaponOverlay weaponOverlay;
  bool initializeAttackPattern;
};

struct CreatureRenderProfileDef {
  CreatureRenderProfile id;
  CreatureRenderAsset asset;
};

inline constexpr std::array<CreatureRenderProfileDef, CRP_COUNT> CREATURE_RENDER_PROFILES = {{
  {CRP_MINNOW, CRA_MINNOW},
  {CRP_PIKE, CRA_PIKE},
  {CRP_FOX, CRA_FOX},
  {CRP_HARE, CRA_HARE},
  {CRP_CRAWLER, CRA_CRAWLER},
  {CRP_MOLE, CRA_MOLE},
  {CRP_BIRD, CRA_BIRD},
  {CRP_BRIAR_GOBLIN, CRA_BRIAR_GOBLIN},
  {CRP_FEN_WITCH, CRA_FEN_WITCH},
  {CRP_BELL_BAT, CRA_BELL_BAT},
  {CRP_OATHLESS_ARCHER, CRA_OATHLESS_ARCHER},
  {CRP_VILLAGER_SCHOLAR, CRA_VILLAGER_SCHOLAR},
  {CRP_STONE_GUARDIAN, CRA_STONE_GUARDIAN},
  {CRP_VILLAGER_KEEPER, CRA_VILLAGER_KEEPER},
  {CRP_VILLAGER_SMITH, CRA_VILLAGER_SMITH},
  {CRP_VILLAGER, CRA_VILLAGER},
  {CRP_FROST_GIANT, CRA_FROST_GIANT},
  {CRP_MUMMY, CRA_MUMMY},
  {CRP_LAVA_TOAD, CRA_LAVA_TOAD},
  {CRP_VILLAGE_GUARD, CRA_VILLAGE_GUARD},
  {CRP_VILLAGE_HUNTER, CRA_VILLAGE_HUNTER},
  {CRP_CINDERJAW_DRAGON, CRA_CINDERJAW_DRAGON},
}};

inline constexpr std::array<CreatureBehaviorProfileDef, CRBH_COUNT> CREATURE_BEHAVIOR_PROFILES = {{
  {CRBH_GENERIC, CAH_GENERIC, CTH_NONE, IK_MATERIAL, CFM_DEFAULT, 0, 0, CWO_NONE, false},
  {CRBH_RANGED, CAH_GENERIC, CTH_NONE, IK_MATERIAL, CFM_DEFAULT, 32, 70, CWO_NONE, false},
  {CRBH_HOVER, CAH_GENERIC, CTH_NONE, IK_MATERIAL, CFM_HOVER, 0, 0, CWO_NONE, false},
}};

inline constexpr std::array<CreatureSpecies, CS_COUNT> CREATURE_SPECIES = {{
  {CS_MINNOW, "minnow", CL_AQUATIC, 4, 2, 18,
   0, 0.34, 0.055, 0, 0,
   0.7, 34, 0,
   0, 18, 18, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_WATER, 3, 84, 2, 20, 180},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_MINNOW, false, CPROT_NONE},
  {CS_PIKE, "pike", CL_AQUATIC, 7, 3, 55,
   0, 0.48, 0.07, 0, 0,
   0.64, 58, 0.6,
   12, 14, 14, 0,
   (uint8_t)(CT_PREY | CT_PLAYER), (1ull << CS_MINNOW), true,
   {CH_WATER, 2, 130, 1, 28, 180},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_PIKE, false, CPROT_NONE},
  {CS_FOX, "fox", CL_AMPHIBIOUS, 7, 4, 42,
   0.34, 0.3, 0.06, 0.075, 1.15,
   0.3, 62, 0.5,
   7, 16, 16, 0,
   (uint8_t)(CT_PREY), (1ull << CS_HARE), false,
   {CH_SURFACE, 1, 96, 1, 28, 180},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_FOREST) | (1u << BIOME_TUNDRA), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_FOX, false, CPROT_NONE},
  {CS_HARE, "hare", CL_AMPHIBIOUS, 5, 3, 24,
   0.34, 0.3, 0.07, 0.075, 1.3,
   0.3, 44, 0,
   0, 0, 20, 46,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 2, 88, 1, 22, 180},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_FOREST) | (1u << BIOME_TUNDRA), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_HARE, false, CPROT_NONE},
  {CS_CRAWLER, "crawler", CL_AMPHIBIOUS, 7, 3, 48,
   0.25, 0.22, 0.052, 0.075, 0.95,
   0.34, 70, 0.7,
   8, 20, 18, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 1, 104, 1, 30, 180},
   {WA_UNDERGROUND, WA_SETTLEMENT, WA_DEEP,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, (1u << CAVE_MUSHROOM) | (1u << CAVE_LUSH) | (1u << CAVE_DEEP_VOID),
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_CRAWLER, false, CPROT_NONE},
  {CS_MOLE, "mole", CL_AMPHIBIOUS, 6, 3, 34,
   0.22, 0.18, 0.048, 0.075, 0.82,
   0.36, 40, 0,
   0, 0, 22, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_CAVE, 1, 112, 1, 34, 180},
   {WA_UNDERGROUND, WA_SETTLEMENT, WA_MINE,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, (1u << CAVE_DEFAULT) | (1u << CAVE_LUSH) | (1u << CAVE_DEEP_FOSSIL),
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_MOLE, false, CPROT_NONE},
  {CS_BIRD, "bird", CL_FLYING, 5, 3, 20,
   0, 0.5, 0.06, 0, 0,
   0, 54, 0,
   0, 0, 20, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_AIR, 2, 96, 1, 20, 180},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_FOREST) | (1u << BIOME_JUNGLE), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_BIRD, false, CPROT_NONE},
  {CS_BRIAR_GOBLIN, "briar goblin", CL_AMPHIBIOUS, 7, 5, 72,
   0.23, 0.17, 0.045, 0.075, 1,
   0.3, 92, 72,
   18, 135, 12, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 128, 1, 34, 220},
   {WA_SURFACE, WA_INDOOR, WA_SETTLEMENT,
    (1u << BIOME_PLAINS) | (1u << BIOME_ROCKY), CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_DESERT) | (1u << BIOME_ROCKY) | (1u << BIOME_TUNDRA), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 2, true, CRBH_GENERIC,
   CRP_BRIAR_GOBLIN, false, CPROT_NONE},
  {CS_FEN_WITCH, "fen witch", CL_AMPHIBIOUS, 8, 6, 120,
   0.16, 0.14, 0.034, 0.075, 0.82,
   0.32, 112, 92,
   16, 180, 10, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 144, 1, 40, 220},
   {WA_SURFACE, WA_INDOOR, 0u,
    (1u << BIOME_DESERT) | (1u << BIOME_SWAMP), CAVE_BIOME_ALL_MASK,
    (1u << BIOME_DESERT) | (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 3, true, CRBH_RANGED,
   CRP_FEN_WITCH, false, CPROT_NONE},
  {CS_OATHLESS_ARCHER, "oathless archer", CL_AMPHIBIOUS, 9, 6, 165,
   0.15, 0.11, 0.03, 0.075, 0.76,
   0.34, 138, 118,
   0, 270, 6, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 1, 156, 1, 44, 220},
   {WA_UNDERGROUND, WA_SETTLEMENT, WA_MINE | WA_FACILITY | WA_DEEP,
    SURFACE_BIOME_ALL_MASK, (1u << CAVE_CRYSTAL) | (1u << CAVE_DEEP_MAGMA) | (1u << CAVE_DEEP_VOID),
    0u, (1u << CAVE_CRYSTAL) | (1u << CAVE_DEEP_MAGMA) | (1u << CAVE_DEEP_VOID),
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 4, true, CRBH_RANGED,
   CRP_OATHLESS_ARCHER, false, CPROT_NONE},
  {CS_VILLAGER_SCHOLAR, "villager scholar", CL_AMPHIBIOUS, 4, 8, 60,
   0.1, 0.14, 0.03, 0.075, 0.7,
   0.34, 28, 0,
   0, 0, 28, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_CAVE, 0, 96, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_VILLAGER_SCHOLAR, true, CPROT_PROTECTED_CREW},
  {CS_STONE_GUARDIAN, "stone guardian", CL_AMPHIBIOUS, 10, 7, 520,
   0.19, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 112,
   30, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_STONE_GUARDIAN, false, CPROT_NONE},
  {CS_VILLAGER_KEEPER, "villager keeper", CL_AMPHIBIOUS, 4, 8, 60,
   0.1, 0.14, 0.03, 0.075, 0.7,
   0.34, 28, 0,
   0, 0, 28, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 0, 96, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_VILLAGER_KEEPER, true, CPROT_ALWAYS},
  {CS_VILLAGER_SMITH, "villager smith", CL_AMPHIBIOUS, 4, 8, 60,
   0.1, 0.14, 0.03, 0.075, 0.7,
   0.34, 28, 0,
   0, 0, 28, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 0, 96, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_VILLAGER_SMITH, true, CPROT_PROTECTED_CREW},
  {CS_VILLAGER, "villager", CL_AMPHIBIOUS, 4, 8, 60,
   0.1, 0.14, 0.03, 0.075, 0.7,
   0.34, 28, 0,
   0, 0, 28, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 0, 72, 0, 0, 0},
   {WA_SETTLEMENT, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, false, CRBH_GENERIC,
   CRP_VILLAGER, true, CPROT_NONE},
  {CS_THORNBOUND_HART, "Thornbound Hart", CL_AMPHIBIOUS, 16, 17, 420,
   0.28, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 90,
   24, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_STONE_GUARDIAN, false, CPROT_NONE},
  {CS_MIRE_MATRON, "Mire Matron", CL_AMPHIBIOUS, 17, 12, 560,
   0.28, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 90,
   24, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_STONE_GUARDIAN, false, CPROT_NONE},
  {CS_CINDER_CASTELLAN, "Cinder Castellan", CL_AMPHIBIOUS, 10, 19, 680,
   0.28, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 90,
   24, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_STONE_GUARDIAN, false, CPROT_NONE},
  {CS_HOLLOW_BELLKEEPER, "Hollow Bellkeeper", CL_AMPHIBIOUS, 11, 23, 850,
   0.28, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 90,
   24, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_STONE_GUARDIAN, false, CPROT_NONE},
  {CS_BRIAR_WOLF, "briar wolf", CL_AMPHIBIOUS, 7, 4, 42,
   0.34, 0.3, 0.06, 0.075, 1.15,
   0.3, 62, 0.5,
   7, 16, 16, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 96, 1, 28, 180},
   {WA_SURFACE, WA_INDOOR, 0u,
    (1u << BIOME_FOREST) | (1u << BIOME_WATCHWOOD) | (1u << BIOME_JUNGLE), CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_FOREST) | (1u << BIOME_TUNDRA), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 3, true, CRBH_GENERIC,
   CRP_FOX, false, CPROT_NONE},
  {CS_BELL_BAT, "bell bat", CL_FLYING, 7, 5, 68,
   0, 0.46, 0.055, 0, 0,
   0, 124, 104,
   0, 210, 10, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_AIR, 1, 144, 1, 38, 220},
   {WA_SURFACE, WA_INDOOR, 0u,
    (1u << BIOME_ROCKY) | (1u << BIOME_WATCHWOOD), CAVE_BIOME_ALL_MASK,
    (1u << BIOME_FOREST) | (1u << BIOME_JUNGLE) | (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 3, true, CRBH_GENERIC,
   CRP_BELL_BAT, false, CPROT_NONE},
  {CS_BONE_GUARD, "bone guard", CL_AMPHIBIOUS, 9, 6, 165,
   0.27, 0.11, 0.03, 0.075, 0.76,
   0.34, 138, 10,
   16, 270, 6, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 1, 156, 1, 44, 220},
   {WA_UNDERGROUND, WA_SETTLEMENT, WA_MINE | WA_FACILITY | WA_DEEP,
    SURFACE_BIOME_ALL_MASK, (1u << CAVE_DEFAULT) | (1u << CAVE_DEEP_FOSSIL) | (1u << CAVE_DEEP_VOID),
    0u, (1u << CAVE_CRYSTAL) | (1u << CAVE_DEEP_MAGMA) | (1u << CAVE_DEEP_VOID),
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 4, true, CRBH_GENERIC,
   CRP_OATHLESS_ARCHER, false, CPROT_NONE},
  {CS_FEN_WISP, "fen wisp", CL_FLYING, 7, 5, 68,
   0, 0.46, 0.055, 0, 0,
   0, 124, 104,
   0, 210, 10, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_AIR, 1, 144, 1, 38, 220},
   {WA_SURFACE, WA_INDOOR, 0u,
    (1u << BIOME_SWAMP) | (1u << BIOME_JUNGLE), CAVE_BIOME_ALL_MASK,
    (1u << BIOME_FOREST) | (1u << BIOME_JUNGLE) | (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 3, true, CRBH_HOVER,
   CRP_BELL_BAT, false, CPROT_NONE},
  {CS_ROOT_KNIGHT, "The Root Knight", CL_AMPHIBIOUS, 8, 13, 280,
   0.19, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 112,
   22, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_STONE_GUARDIAN, false, CPROT_NONE},
  {CS_FROST_GIANT, "frost giant", CL_AMPHIBIOUS, 12, 19, 240,
   0.16, 0.14, 0.038, 0.075, 0.92,
   0.32, 110, 66,
   26, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 160, 1, 48, 280},
   {WA_SURFACE, WA_SETTLEMENT, 0u,
    (1u << BIOME_TUNDRA), CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 7, true, CRBH_GENERIC,
   CRP_FROST_GIANT, false, CPROT_NONE},
  {CS_MUMMY, "mummy", CL_AMPHIBIOUS, 5, 10, 90,
   0.23, 0.11, 0.03, 0.075, 0.76,
   0.34, 80, 12,
   18, 270, 6, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 160, 1, 48, 280},
   {0u, WA_SETTLEMENT, 0u,
    (1u << BIOME_DESERT), CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 16, 20},
   CPOP_ENCOUNTER, 3, true, CRBH_GENERIC,
   CRP_MUMMY, false, CPROT_NONE},
  {CS_LAVA_TOAD, "lava toad", CL_AMPHIBIOUS, 9, 7, 125,
   0.18, 0.14, 0.038, 0.075, 0.92,
   0.32, 105, 60,
   20, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 1, 160, 1, 48, 280},
   {WA_UNDERGROUND, WA_SETTLEMENT, 0u,
    SURFACE_BIOME_ALL_MASK, (1u << CAVE_DEEP_MAGMA),
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 5, true, CRBH_GENERIC,
   CRP_LAVA_TOAD, false, CPROT_NONE},
  {CS_VILLAGE_GUARD, "village guard", CL_AMPHIBIOUS, 4, 8, 120,
   0.23, 0.14, 0.03, 0.075, 0.7,
   0.34, 64, 10,
   20, 0, 28, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 0, 160, 0, 48, 280},
   {WA_SETTLEMENT, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, false, CRBH_GENERIC,
   CRP_VILLAGE_GUARD, true, CPROT_NONE},
  {CS_VILLAGE_HUNTER, "village hunter", CL_AMPHIBIOUS, 4, 8, 85,
   0.25, 0.14, 0.03, 0.075, 0.7,
   0.34, 80, 48,
   15, 0, 28, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 0, 160, 0, 48, 280},
   {WA_SETTLEMENT, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, false, CRBH_GENERIC,
   CRP_VILLAGE_HUNTER, true, CPROT_NONE},
  {CS_CINDERJAW_DRAGON, "cinderjaw dragon", CL_AMPHIBIOUS, 24, 22, 320,
   0.34, 0.12, 0.045, 0.075, 1.05,
   0.32, 120, 24,
   34, 0, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 220, 1, 48, 280},
   {WA_SURFACE, WA_SETTLEMENT, 0u,
    (1u << BIOME_ROCKY), CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 8, true, CRBH_GENERIC,
   CRP_CINDERJAW_DRAGON, false, CPROT_NONE},
}};

inline constexpr std::array<uint8_t, 7> AMBIENT_CREATURE_SPECIES = {{
  CS_MINNOW, CS_PIKE, CS_FOX, CS_HARE, CS_CRAWLER, CS_MOLE, CS_BIRD,
}};
inline constexpr std::array<uint8_t, 11> ENCOUNTER_CREATURE_SPECIES = {{
  CS_BRIAR_GOBLIN, CS_FEN_WITCH, CS_OATHLESS_ARCHER, CS_BRIAR_WOLF, CS_BELL_BAT, CS_BONE_GUARD, CS_FEN_WISP, CS_FROST_GIANT, CS_MUMMY, CS_LAVA_TOAD, CS_CINDERJAW_DRAGON,
}};

template <size_t N>
constexpr bool creatureBehaviorProfilesAreValid(
    const std::array<CreatureBehaviorProfileDef, N>& profiles) {
  if (N != CRBH_COUNT) return false;
  for (size_t index = 0; index < N; index++) {
    const CreatureBehaviorProfileDef& behavior = profiles[index];
    if ((size_t)behavior.id != index
        || (unsigned)behavior.attack >= CAH_COUNT
        || (unsigned)behavior.telegraph >= CTH_COUNT
        || (unsigned)behavior.flyingMovement >= CFM_COUNT
        || (unsigned)behavior.weaponOverlay >= CWO_COUNT) return false;
  }
  return true;
}

constexpr bool creatureRegistriesAreComplete() {
  if (!creatureBehaviorProfilesAreValid(CREATURE_BEHAVIOR_PROFILES))
    return false;
  for (size_t index = 0; index < CREATURE_RENDER_PROFILES.size(); index++) {
    const CreatureRenderProfileDef& render = CREATURE_RENDER_PROFILES[index];
    if ((size_t)render.id != index
        || (unsigned)render.asset >= CRA_COUNT) return false;
  }
  for (size_t index = 0; index < CREATURE_SPECIES.size(); index++) {
    const CreatureSpecies& species = CREATURE_SPECIES[index];
    if ((size_t)species.id != index
        || (unsigned)species.population >= CPOP_COUNT
        || (unsigned)species.behaviorProfile >= CRBH_COUNT
        || (unsigned)species.renderProfile >= CRP_COUNT
        || (unsigned)species.protection >= CPROT_COUNT) return false;
  }
  return true;
}
static_assert(creatureRegistriesAreComplete(),
              "Creature descriptors and behavior profiles must be dense and exhaustive");

constexpr bool creatureBehaviorInvalidFixturesAreRejected() {
  auto fixture = CREATURE_BEHAVIOR_PROFILES;
  fixture[0].attack = (CreatureAttackHandler)CAH_COUNT;
  if (creatureBehaviorProfilesAreValid(fixture)) return false;
  fixture = CREATURE_BEHAVIOR_PROFILES;
  fixture[0].id = fixture[1].id;
  return !creatureBehaviorProfilesAreValid(fixture);
}
static_assert(creatureBehaviorInvalidFixturesAreRejected(),
              "Invalid creature behavior selectors must fail validation");

inline const CreatureBehaviorProfileDef& creatureBehaviorProfile(
    CreatureBehaviorProfile profile) {
  if ((unsigned)profile < CREATURE_BEHAVIOR_PROFILES.size())
    return CREATURE_BEHAVIOR_PROFILES[(size_t)profile];
  __builtin_trap();
}

inline const CreatureBehaviorProfileDef& creatureBehavior(
    const CreatureSpecies& species) {
  return creatureBehaviorProfile(
    (CreatureBehaviorProfile)species.behaviorProfile);
}

inline const CreatureRenderProfileDef& creatureRenderProfile(
    const CreatureSpecies& species) {
  if ((unsigned)species.renderProfile < CREATURE_RENDER_PROFILES.size())
    return CREATURE_RENDER_PROFILES[(size_t)species.renderProfile];
  __builtin_trap();
}

inline bool isAmbientSpecies(uint8_t speciesId) {
  return speciesId < CS_COUNT
    && CREATURE_SPECIES[(size_t)speciesId].population == CPOP_AMBIENT;
}

inline bool isEncounterSpecies(uint8_t speciesId) {
  return speciesId < CS_COUNT
    && CREATURE_SPECIES[(size_t)speciesId].population == CPOP_ENCOUNTER;
}
