// GENERATED by scripts/generate-abi.mjs — DO NOT EDIT.
// Creature ids, simulation/population descriptors, render metadata, and exhaustive behavior policies.
#pragma once

enum CreatureSpeciesId : uint8_t {
  CS_MINNOW = CREATURE_MINNOW,
  CS_PIKE = CREATURE_PIKE,
  CS_FOX = CREATURE_FOX,
  CS_HARE = CREATURE_HARE,
  CS_CRAWLER = CREATURE_CRAWLER,
  CS_MOLE = CREATURE_MOLE,
  CS_BIRD = CREATURE_BIRD,
  CS_DYNAMITEER = CREATURE_DYNAMITEER,
  CS_BORE_SENTINEL = CREATURE_BORE_SENTINEL,
  CS_CAUSTIC_MORTARMAN = CREATURE_CAUSTIC_MORTARMAN,
  CS_CLUSTER_WASP = CREATURE_CLUSTER_WASP,
  CS_MINIGUNNER = CREATURE_MINIGUNNER,
  CS_SURVEYOR = CREATURE_SURVEYOR,
  CS_SHIELD_ANCHOR = CREATURE_SHIELD_ANCHOR,
  CS_QUARRY_FOREMAN = CREATURE_QUARRY_FOREMAN,
  CS_REACTOR_WARDEN = CREATURE_REACTOR_WARDEN,
  CS_REACTOR_CORE = CREATURE_REACTOR_CORE,
  CS_IRIS_COMMANDER = CREATURE_IRIS_COMMANDER,
  CS_IRIS_ENGINEER = CREATURE_IRIS_ENGINEER,
  CS_VILLAGER = CREATURE_VILLAGER,
  CS_THORNBOUND_HART = CREATURE_THORNBOUND_HART,
  CS_MIRE_MATRON = CREATURE_MIRE_MATRON,
  CS_CINDER_CASTELLAN = CREATURE_CINDER_CASTELLAN,
  CS_HOLLOW_BELLKEEPER = CREATURE_HOLLOW_BELLKEEPER,
  CS_BRIAR_WOLF = CREATURE_BRIAR_WOLF,
  CS_BELL_BAT = CREATURE_BELL_BAT,
  CS_BONE_GUARD = CREATURE_BONE_GUARD,
  CS_FEN_WISP = CREATURE_FEN_WISP,
  CS_ROOT_KNIGHT = CREATURE_ROOT_KNIGHT,
  CS_COUNT = 29,
};

enum CreaturePopulationProfile : uint8_t { CPOP_AMBIENT = 0, CPOP_ENCOUNTER, CPOP_SCRIPTED, CPOP_COUNT };
enum CreatureRenderBob : uint8_t { CRB_NONE = 0, CRB_WALKER, CRB_AQUATIC, CRB_BIRD, CRB_WASP, CRB_HARE, CRB_COUNT };
enum CreatureProtection : uint8_t { CPROT_NONE = 0, CPROT_ALWAYS, CPROT_PROTECTED_CREW, CPROT_COUNT };

enum CreatureBehaviorProfile : uint8_t {
  CRBH_GENERIC = 0,
  CRBH_DYNAMITEER = 1,
  CRBH_BORE_SENTINEL = 2,
  CRBH_CAUSTIC_MORTARMAN = 3,
  CRBH_CLUSTER_WASP = 4,
  CRBH_MINIGUNNER = 5,
  CRBH_QUARRY_FOREMAN = 6,
  CRBH_REACTOR_WARDEN = 7,
  CRBH_COUNT = 8,
};

enum CreatureRenderProfile : uint8_t {
  CRP_MINNOW = 0,
  CRP_PIKE = 1,
  CRP_FOX = 2,
  CRP_HARE = 3,
  CRP_CRAWLER = 4,
  CRP_MOLE = 5,
  CRP_BIRD = 6,
  CRP_DYNAMITEER = 7,
  CRP_BORE_SENTINEL = 8,
  CRP_CAUSTIC_MORTARMAN = 9,
  CRP_CLUSTER_WASP = 10,
  CRP_MINIGUNNER = 11,
  CRP_SURVEYOR = 12,
  CRP_SHIELD_ANCHOR = 13,
  CRP_QUARRY_FOREMAN = 14,
  CRP_REACTOR_WARDEN = 15,
  CRP_REACTOR_CORE = 16,
  CRP_IRIS_COMMANDER = 17,
  CRP_IRIS_ENGINEER = 18,
  CRP_VILLAGER = 19,
  CRP_COUNT = 20,
};

enum CreatureRenderAsset : uint8_t {
  CRA_MINNOW = 0,
  CRA_PIKE = 1,
  CRA_FOX = 2,
  CRA_HARE = 3,
  CRA_CRAWLER = 4,
  CRA_MOLE = 5,
  CRA_BIRD = 6,
  CRA_DYNAMITEER = 7,
  CRA_BORE_SENTINEL = 8,
  CRA_CAUSTIC_MORTARMAN = 9,
  CRA_CLUSTER_WASP = 10,
  CRA_MINIGUNNER = 11,
  CRA_SURVEYOR = 12,
  CRA_SHIELD_ANCHOR = 13,
  CRA_QUARRY_FOREMAN = 14,
  CRA_REACTOR_WARDEN = 15,
  CRA_REACTOR_CORE = 16,
  CRA_IRIS_COMMANDER = 17,
  CRA_IRIS_ENGINEER = 18,
  CRA_VILLAGER = 19,
  CRA_COUNT = 20,
};

enum CreatureAttackHandler : uint8_t {
  CAH_GENERIC = 0,
  CAH_DYNAMITEER = 1,
  CAH_BORE_SENTINEL = 2,
  CAH_CAUSTIC_MORTARMAN = 3,
  CAH_CLUSTER_WASP = 4,
  CAH_MINIGUNNER = 5,
  CAH_BOSS = 6,
  CAH_COUNT = 7,
};
enum CreatureTelegraphHandler : uint8_t {
  CTH_NONE = 0,
  CTH_BORE = 1,
  CTH_MORTAR = 2,
  CTH_CLUSTER = 3,
  CTH_QUARRY = 4,
  CTH_WARDEN = 5,
  CTH_COUNT = 6,
};
enum CreatureAnimationProfile : uint8_t {
  CAP_GENERIC = 0,
  CAP_DYNAMITE = 1,
  CAP_BORE = 2,
  CAP_MORTAR = 3,
  CAP_WASP = 4,
  CAP_MINIGUN = 5,
  CAP_COUNT = 6,
};
enum CreatureFlyingMovement : uint8_t {
  CFM_DEFAULT = 0,
  CFM_CLUSTER = 1,
  CFM_COUNT = 2,
};
enum CreatureWeaponOverlay : uint8_t {
  CWO_NONE = 0,
  CWO_MINIGUN = 1,
  CWO_COUNT = 2,
};

struct CreatureBehaviorProfileDef {
  CreatureBehaviorProfile id;
  CreatureAttackHandler attack;
  CreatureTelegraphHandler telegraph;
  InventoryItemKind dropItem;
  CreatureAnimationProfile animation;
  CreatureFlyingMovement flyingMovement;
  int nearRange, farRange;
  CreatureWeaponOverlay weaponOverlay;
  bool initializeAttackPattern;
};

struct CreatureRenderProfileDef {
  CreatureRenderProfile id;
  CreatureRenderAsset asset;
};

inline constexpr std::array<CreatureRenderProfileDef, CRP_COUNT> CREATURE_RENDER_PROFILES = {{
  {CRP_MINNOW, CRA_MINNOW},
  {CRP_PIKE, CRA_PIKE},
  {CRP_FOX, CRA_FOX},
  {CRP_HARE, CRA_HARE},
  {CRP_CRAWLER, CRA_CRAWLER},
  {CRP_MOLE, CRA_MOLE},
  {CRP_BIRD, CRA_BIRD},
  {CRP_DYNAMITEER, CRA_DYNAMITEER},
  {CRP_BORE_SENTINEL, CRA_BORE_SENTINEL},
  {CRP_CAUSTIC_MORTARMAN, CRA_CAUSTIC_MORTARMAN},
  {CRP_CLUSTER_WASP, CRA_CLUSTER_WASP},
  {CRP_MINIGUNNER, CRA_MINIGUNNER},
  {CRP_SURVEYOR, CRA_SURVEYOR},
  {CRP_SHIELD_ANCHOR, CRA_SHIELD_ANCHOR},
  {CRP_QUARRY_FOREMAN, CRA_QUARRY_FOREMAN},
  {CRP_REACTOR_WARDEN, CRA_REACTOR_WARDEN},
  {CRP_REACTOR_CORE, CRA_REACTOR_CORE},
  {CRP_IRIS_COMMANDER, CRA_IRIS_COMMANDER},
  {CRP_IRIS_ENGINEER, CRA_IRIS_ENGINEER},
  {CRP_VILLAGER, CRA_VILLAGER},
}};

inline constexpr std::array<CreatureBehaviorProfileDef, CRBH_COUNT> CREATURE_BEHAVIOR_PROFILES = {{
  {CRBH_GENERIC, CAH_GENERIC, CTH_NONE, IK_MATERIAL, CAP_GENERIC, CFM_DEFAULT, 0, 0, CWO_NONE, false},
  {CRBH_DYNAMITEER, CAH_DYNAMITEER, CTH_NONE, IK_DYNAMITE_SATCHEL, CAP_DYNAMITE, CFM_DEFAULT, 28, 58, CWO_NONE, false},
  {CRBH_BORE_SENTINEL, CAH_BORE_SENTINEL, CTH_BORE, IK_BORE_CANNON, CAP_BORE, CFM_DEFAULT, 46, 88, CWO_NONE, false},
  {CRBH_CAUSTIC_MORTARMAN, CAH_CAUSTIC_MORTARMAN, CTH_MORTAR, IK_ACID_MORTAR, CAP_MORTAR, CFM_DEFAULT, 36, 76, CWO_NONE, false},
  {CRBH_CLUSTER_WASP, CAH_CLUSTER_WASP, CTH_CLUSTER, IK_CLUSTER_LAUNCHER, CAP_WASP, CFM_CLUSTER, 0, 0, CWO_NONE, false},
  {CRBH_MINIGUNNER, CAH_MINIGUNNER, CTH_NONE, IK_MINIGUN, CAP_MINIGUN, CFM_DEFAULT, 38, 92, CWO_MINIGUN, false},
  {CRBH_QUARRY_FOREMAN, CAH_BOSS, CTH_QUARRY, IK_DYNAMITE_SATCHEL, CAP_DYNAMITE, CFM_DEFAULT, 28, 58, CWO_NONE, true},
  {CRBH_REACTOR_WARDEN, CAH_BOSS, CTH_WARDEN, IK_MINIGUN, CAP_MINIGUN, CFM_DEFAULT, 38, 92, CWO_MINIGUN, true},
}};

inline constexpr std::array<CreatureSpecies, CS_COUNT> CREATURE_SPECIES = {{
  {CS_MINNOW, "minnow", CL_AQUATIC, 4, 2, 18,
   0, 0.34, 0.055, 0, 0,
   0.7, 34, 0,
   0, 18, 18, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_WATER, 3, 84, 2, 20, 180},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_MINNOW, false, CRB_AQUATIC, false, CPROT_NONE},
  {CS_PIKE, "pike", CL_AQUATIC, 7, 3, 55,
   0, 0.48, 0.07, 0, 0,
   0.64, 58, 0.6,
   12, 14, 14, 0,
   (uint8_t)(CT_PREY | CT_PLAYER), (1u << CS_MINNOW), true,
   {CH_WATER, 2, 130, 1, 28, 180},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_PIKE, false, CRB_AQUATIC, false, CPROT_NONE},
  {CS_FOX, "fox", CL_AMPHIBIOUS, 7, 4, 42,
   0.34, 0.3, 0.06, 0.075, 1.15,
   0.3, 62, 0.5,
   7, 16, 16, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 96, 1, 28, 180},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_FOREST) | (1u << BIOME_TUNDRA), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_FOX, false, CRB_WALKER, false, CPROT_NONE},
  {CS_HARE, "hare", CL_AMPHIBIOUS, 5, 3, 24,
   0.34, 0.3, 0.07, 0.075, 1.3,
   0.3, 44, 0,
   0, 0, 20, 46,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 2, 88, 1, 22, 180},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_FOREST) | (1u << BIOME_TUNDRA), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_HARE, false, CRB_HARE, false, CPROT_NONE},
  {CS_CRAWLER, "crawler", CL_AMPHIBIOUS, 7, 3, 48,
   0.25, 0.22, 0.052, 0.075, 0.95,
   0.34, 70, 0.7,
   8, 20, 18, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 1, 104, 1, 30, 180},
   {WA_UNDERGROUND, WA_SETTLEMENT, WA_DEEP,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, (1u << CAVE_MUSHROOM) | (1u << CAVE_LUSH) | (1u << CAVE_DEEP_VOID),
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_CRAWLER, false, CRB_WALKER, false, CPROT_NONE},
  {CS_MOLE, "mole", CL_AMPHIBIOUS, 6, 3, 34,
   0.22, 0.18, 0.048, 0.075, 0.82,
   0.36, 40, 0,
   0, 0, 22, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_CAVE, 1, 112, 1, 34, 180},
   {WA_UNDERGROUND, WA_SETTLEMENT, WA_MINE,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, (1u << CAVE_DEFAULT) | (1u << CAVE_LUSH) | (1u << CAVE_DEEP_FOSSIL),
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_MOLE, false, CRB_WALKER, false, CPROT_NONE},
  {CS_BIRD, "bird", CL_FLYING, 5, 3, 20,
   0, 0.5, 0.06, 0, 0,
   0, 54, 0,
   0, 0, 20, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_AIR, 2, 96, 1, 20, 180},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_FOREST) | (1u << BIOME_JUNGLE), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_BIRD, false, CRB_BIRD, false, CPROT_NONE},
  {CS_DYNAMITEER, "dynamiteer", CL_AMPHIBIOUS, 7, 5, 72,
   0.23, 0.17, 0.045, 0.075, 1,
   0.3, 92, 72,
   18, 135, 12, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 128, 1, 34, 220},
   {WA_SURFACE, WA_INDOOR, WA_SETTLEMENT,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_DESERT) | (1u << BIOME_ROCKY) | (1u << BIOME_TUNDRA), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 2, true, CRBH_DYNAMITEER,
   CRP_DYNAMITEER, false, CRB_WALKER, false, CPROT_NONE},
  {CS_BORE_SENTINEL, "bore sentinel", CL_AMPHIBIOUS, 9, 6, 170,
   0.12, 0.11, 0.026, 0.075, 0.72,
   0.34, 138, 118,
   42, 260, 10, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 1, 156, 1, 46, 220},
   {WA_UNDERGROUND, WA_SETTLEMENT, WA_MINE | WA_DEEP,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, (1u << CAVE_DEEP_GEODE) | (1u << CAVE_DEEP_FOSSIL),
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 4, true, CRBH_BORE_SENTINEL,
   CRP_BORE_SENTINEL, false, CRB_WALKER, false, CPROT_NONE},
  {CS_CAUSTIC_MORTARMAN, "caustic mortarman", CL_AMPHIBIOUS, 8, 6, 120,
   0.16, 0.14, 0.034, 0.075, 0.82,
   0.32, 112, 92,
   16, 180, 10, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 144, 1, 40, 220},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_DESERT) | (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 3, true, CRBH_CAUSTIC_MORTARMAN,
   CRP_CAUSTIC_MORTARMAN, false, CRB_WALKER, false, CPROT_NONE},
  {CS_CLUSTER_WASP, "cluster wasp", CL_FLYING, 7, 5, 68,
   0, 0.46, 0.055, 0, 0,
   0, 124, 104,
   0, 210, 10, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_AIR, 1, 144, 1, 38, 220},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_FOREST) | (1u << BIOME_JUNGLE) | (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 3, true, CRBH_CLUSTER_WASP,
   CRP_CLUSTER_WASP, false, CRB_WASP, false, CPROT_NONE},
  {CS_MINIGUNNER, "minigunner", CL_AMPHIBIOUS, 9, 6, 165,
   0.15, 0.11, 0.03, 0.075, 0.76,
   0.34, 138, 118,
   0, 270, 6, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 1, 156, 1, 44, 220},
   {WA_UNDERGROUND, WA_SETTLEMENT, WA_MINE | WA_FACILITY | WA_DEEP,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, (1u << CAVE_CRYSTAL) | (1u << CAVE_DEEP_MAGMA) | (1u << CAVE_DEEP_VOID),
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 4, true, CRBH_MINIGUNNER,
   CRP_MINIGUNNER, false, CRB_WALKER, false, CPROT_NONE},
  {CS_SURVEYOR, "surveyor", CL_AMPHIBIOUS, 4, 8, 70,
   0.12, 0.16, 0.036, 0.075, 0.72,
   0.34, 36, 0,
   0, 0, 24, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_CAVE, 0, 96, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_SURVEYOR, true, CRB_WALKER, false, CPROT_PROTECTED_CREW},
  {CS_SHIELD_ANCHOR, "shield anchor", CL_STATIONARY, 7, 7, 210,
   0, 0, 0, 0, 0,
   0, 0, 0,
   0, 0, 60, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_CAVE, 0, 96, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_SHIELD_ANCHOR, false, CRB_WALKER, true, CPROT_NONE},
  {CS_QUARRY_FOREMAN, "quarry foreman", CL_AMPHIBIOUS, 10, 7, 520,
   0.19, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 112,
   30, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_QUARRY_FOREMAN,
   CRP_QUARRY_FOREMAN, false, CRB_WALKER, false, CPROT_NONE},
  {CS_REACTOR_WARDEN, "reactor warden", CL_AMPHIBIOUS, 11, 8, 760,
   0.13, 0.1, 0.028, 0.075, 0.72,
   0.34, 162, 132,
   0, 190, 5, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 180, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_REACTOR_WARDEN,
   CRP_REACTOR_WARDEN, false, CRB_WALKER, false, CPROT_NONE},
  {CS_REACTOR_CORE, "reactor core", CL_STATIONARY, 9, 12, 460,
   0, 0, 0, 0, 0,
   0, 0, 0,
   0, 0, 60, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_CAVE, 0, 96, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_REACTOR_CORE, false, CRB_WALKER, true, CPROT_NONE},
  {CS_IRIS_COMMANDER, "IRIS commander", CL_STATIONARY, 4, 8, 100,
   0, 0, 0, 0, 0,
   0, 0, 0,
   0, 0, 60, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 0, 96, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_IRIS_COMMANDER, true, CRB_NONE, false, CPROT_ALWAYS},
  {CS_IRIS_ENGINEER, "IRIS engineer", CL_STATIONARY, 4, 8, 100,
   0, 0, 0, 0, 0,
   0, 0, 0,
   0, 0, 60, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 0, 96, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_GENERIC,
   CRP_IRIS_ENGINEER, true, CRB_NONE, false, CPROT_PROTECTED_CREW},
  {CS_VILLAGER, "villager", CL_AMPHIBIOUS, 4, 8, 60,
   0.1, 0.14, 0.03, 0.075, 0.7,
   0.34, 28, 0,
   0, 0, 28, 0,
   (uint8_t)(CT_NONE), 0u, false,
   {CH_SURFACE, 0, 72, 0, 0, 0},
   {WA_SETTLEMENT, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, false, CRBH_GENERIC,
   CRP_VILLAGER, true, CRB_WALKER, false, CPROT_NONE},
  {CS_THORNBOUND_HART, "Thornbound Hart", CL_AMPHIBIOUS, 16, 17, 420,
   0.28, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 90,
   24, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_QUARRY_FOREMAN,
   CRP_QUARRY_FOREMAN, false, CRB_WALKER, false, CPROT_NONE},
  {CS_MIRE_MATRON, "Mire Matron", CL_AMPHIBIOUS, 17, 12, 560,
   0.28, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 90,
   24, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_QUARRY_FOREMAN,
   CRP_QUARRY_FOREMAN, false, CRB_WALKER, false, CPROT_NONE},
  {CS_CINDER_CASTELLAN, "Cinder Castellan", CL_AMPHIBIOUS, 10, 19, 680,
   0.28, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 90,
   24, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_QUARRY_FOREMAN,
   CRP_QUARRY_FOREMAN, false, CRB_WALKER, false, CPROT_NONE},
  {CS_HOLLOW_BELLKEEPER, "Hollow Bellkeeper", CL_AMPHIBIOUS, 11, 23, 850,
   0.28, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 90,
   24, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_QUARRY_FOREMAN,
   CRP_QUARRY_FOREMAN, false, CRB_WALKER, false, CPROT_NONE},
  {CS_BRIAR_WOLF, "briar wolf", CL_AMPHIBIOUS, 7, 4, 42,
   0.34, 0.3, 0.06, 0.075, 1.15,
   0.3, 62, 0.5,
   7, 16, 16, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_SURFACE, 1, 96, 1, 28, 180},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_PLAINS) | (1u << BIOME_FOREST) | (1u << BIOME_TUNDRA), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_AMBIENT, 0, true, CRBH_GENERIC,
   CRP_FOX, false, CRB_WALKER, false, CPROT_NONE},
  {CS_BELL_BAT, "bell bat", CL_FLYING, 7, 5, 68,
   0, 0.46, 0.055, 0, 0,
   0, 124, 104,
   0, 210, 10, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_AIR, 1, 144, 1, 38, 220},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_FOREST) | (1u << BIOME_JUNGLE) | (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 3, true, CRBH_CLUSTER_WASP,
   CRP_CLUSTER_WASP, false, CRB_WASP, false, CPROT_NONE},
  {CS_BONE_GUARD, "bone guard", CL_AMPHIBIOUS, 9, 6, 165,
   0.15, 0.11, 0.03, 0.075, 0.76,
   0.34, 138, 118,
   0, 270, 6, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 1, 156, 1, 44, 220},
   {WA_UNDERGROUND, WA_SETTLEMENT, WA_MINE | WA_FACILITY | WA_DEEP,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, (1u << CAVE_CRYSTAL) | (1u << CAVE_DEEP_MAGMA) | (1u << CAVE_DEEP_VOID),
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 4, true, CRBH_MINIGUNNER,
   CRP_MINIGUNNER, false, CRB_WALKER, false, CPROT_NONE},
  {CS_FEN_WISP, "fen wisp", CL_FLYING, 7, 5, 68,
   0, 0.46, 0.055, 0, 0,
   0, 124, 104,
   0, 210, 10, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_AIR, 1, 144, 1, 38, 220},
   {WA_SURFACE, WA_INDOOR, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    (1u << BIOME_FOREST) | (1u << BIOME_JUNGLE) | (1u << BIOME_SWAMP), 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_ENCOUNTER, 3, true, CRBH_CLUSTER_WASP,
   CRP_CLUSTER_WASP, false, CRB_WASP, false, CPROT_NONE},
  {CS_ROOT_KNIGHT, "The Root Knight", CL_AMPHIBIOUS, 8, 13, 280,
   0.19, 0.14, 0.038, 0.075, 0.92,
   0.32, 148, 112,
   22, 105, 8, 0,
   (uint8_t)(CT_PLAYER), 0u, true,
   {CH_CAVE, 0, 160, 0, 0, 0},
   {0u, 0u, 0u,
    SURFACE_BIOME_ALL_MASK, CAVE_BIOME_ALL_MASK,
    0u, 0u,
    INT_MIN, INT_MAX, 10, 20},
   CPOP_SCRIPTED, 0, true, CRBH_QUARRY_FOREMAN,
   CRP_QUARRY_FOREMAN, false, CRB_WALKER, false, CPROT_NONE},
}};

inline constexpr std::array<uint8_t, 8> AMBIENT_CREATURE_SPECIES = {{
  CS_MINNOW, CS_PIKE, CS_FOX, CS_HARE, CS_CRAWLER, CS_MOLE, CS_BIRD, CS_BRIAR_WOLF,
}};
inline constexpr std::array<uint8_t, 8> ENCOUNTER_CREATURE_SPECIES = {{
  CS_DYNAMITEER, CS_BORE_SENTINEL, CS_CAUSTIC_MORTARMAN, CS_CLUSTER_WASP, CS_MINIGUNNER, CS_BELL_BAT, CS_BONE_GUARD, CS_FEN_WISP,
}};

template <size_t N>
constexpr bool creatureBehaviorProfilesAreValid(
    const std::array<CreatureBehaviorProfileDef, N>& profiles) {
  if (N != CRBH_COUNT) return false;
  for (size_t index = 0; index < N; index++) {
    const CreatureBehaviorProfileDef& behavior = profiles[index];
    if ((size_t)behavior.id != index
        || (unsigned)behavior.attack >= CAH_COUNT
        || (unsigned)behavior.telegraph >= CTH_COUNT
        || (unsigned)behavior.animation >= CAP_COUNT
        || (unsigned)behavior.flyingMovement >= CFM_COUNT
        || (unsigned)behavior.weaponOverlay >= CWO_COUNT) return false;
  }
  return true;
}

constexpr bool creatureRegistriesAreComplete() {
  if (!creatureBehaviorProfilesAreValid(CREATURE_BEHAVIOR_PROFILES))
    return false;
  for (size_t index = 0; index < CREATURE_RENDER_PROFILES.size(); index++) {
    const CreatureRenderProfileDef& render = CREATURE_RENDER_PROFILES[index];
    if ((size_t)render.id != index
        || (unsigned)render.asset >= CRA_COUNT) return false;
  }
  for (size_t index = 0; index < CREATURE_SPECIES.size(); index++) {
    const CreatureSpecies& species = CREATURE_SPECIES[index];
    if ((size_t)species.id != index
        || (unsigned)species.population >= CPOP_COUNT
        || (unsigned)species.behaviorProfile >= CRBH_COUNT
        || (unsigned)species.renderProfile >= CRP_COUNT
        || (unsigned)species.renderBob >= CRB_COUNT
        || (unsigned)species.protection >= CPROT_COUNT) return false;
  }
  return true;
}
static_assert(creatureRegistriesAreComplete(),
              "Creature descriptors and behavior profiles must be dense and exhaustive");

constexpr bool creatureBehaviorInvalidFixturesAreRejected() {
  auto fixture = CREATURE_BEHAVIOR_PROFILES;
  fixture[0].attack = (CreatureAttackHandler)CAH_COUNT;
  if (creatureBehaviorProfilesAreValid(fixture)) return false;
  fixture = CREATURE_BEHAVIOR_PROFILES;
  fixture[0].id = fixture[1].id;
  return !creatureBehaviorProfilesAreValid(fixture);
}
static_assert(creatureBehaviorInvalidFixturesAreRejected(),
              "Invalid creature behavior selectors must fail validation");

inline const CreatureBehaviorProfileDef& creatureBehaviorProfile(
    CreatureBehaviorProfile profile) {
  if ((unsigned)profile < CREATURE_BEHAVIOR_PROFILES.size())
    return CREATURE_BEHAVIOR_PROFILES[(size_t)profile];
  __builtin_trap();
}

inline const CreatureBehaviorProfileDef& creatureBehavior(
    const CreatureSpecies& species) {
  return creatureBehaviorProfile(
    (CreatureBehaviorProfile)species.behaviorProfile);
}

inline const CreatureRenderProfileDef& creatureRenderProfile(
    const CreatureSpecies& species) {
  if ((unsigned)species.renderProfile < CREATURE_RENDER_PROFILES.size())
    return CREATURE_RENDER_PROFILES[(size_t)species.renderProfile];
  __builtin_trap();
}

inline bool isAmbientSpecies(uint8_t speciesId) {
  return speciesId < CS_COUNT
    && CREATURE_SPECIES[(size_t)speciesId].population == CPOP_AMBIENT;
}

inline bool isEncounterSpecies(uint8_t speciesId) {
  return speciesId < CS_COUNT
    && CREATURE_SPECIES[(size_t)speciesId].population == CPOP_ENCOUNTER;
}
