#pragma once
// Generated by scripts/generate-reactions.mjs from reactions.schema.json.
// The persistent age channel exists only when a production rule consumes it.

#define SAND_HAS_REACTION_AGE_CHANNEL 0
#if SAND_HAS_REACTION_AGE_CHANNEL
#define SAND_REACTION_AGE_CHANNEL(X) \
  X(reactionAge, uint32_t, 0, reactionAgeStore, encodeVelocityTile, decodeVelocityTile, persistentReactionAgeState, PCSO_STATIONARY | PCSO_MOVE | PCSO_SWAP | PCSO_CROSS_LAYER | PCSO_FORCE_PARK | PCSO_BODY_DISPLACE)
#else
#define SAND_REACTION_AGE_CHANNEL(X)
#endif
