// Pixel sources keyed by creature identity. Frames are editable without WASM.
export default {
  "MINNOW": {
    "width": 26,
    "height": 14,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "t": "#287578",
      "T": "#4eaaa0",
      "w": "#c8e0c5",
      "g": "#c88b49",
      "G": "#f1ce7a",
      "c": "#74c9d0"
    },
    "frames": [
      [
        "..............o...........",
        ".............oto..........",
        "...........ootttooo.......",
        "....oo...ooTTttttTToo.....",
        "...ottoooTTTTTTccccTTo....",
        "...ottttTTTccccttttTTGoo..",
        "...otttTTTTttttTTTTTToTTo.",
        "...otttTTTTTTTTTwwwwwwTTo.",
        "...otttTTTwwwwwwwwwwwwbbbo",
        "...ottttTTTTwgwwwwwwwTooo.",
        "...ottooooTTTgTTTooooo....",
        "....oo....oogoooo.........",
        "...........ogo............",
        "............o............."
      ],
      [
        "..............o...........",
        ".............oto..........",
        "....o......ootttooo.......",
        "...otoo..ooTTttttTToo.....",
        "...otttooTTTTTTccccTTo....",
        "...ottttTTTccccttttTTGoo..",
        "...otttTTTTttttTTTTTToTTo.",
        "...otttTTTTTTTTTwwwwwwTTo.",
        "...otttTTTwwwwwwwwwwwwbbbo",
        "...otttoTTTTwgwwwwwwwTooo.",
        "...otoo.ooTTTgTTTooooo....",
        "....o.....ooogooo.........",
        "............ogo...........",
        ".............o............"
      ],
      [
        "..............o...........",
        ".............oto..........",
        "...........ootttooo.......",
        "....oo...ooTTttttTToo.....",
        "...ottoooTTTTTTccccTTo....",
        "...ottttTTTccccttttTTGoo..",
        "...otttTTTTttttTTTTTToTTo.",
        "...otttTTTTTTTTTwwwwwwTTo.",
        "...otttTTTwwwwwwwwwwwwbbbo",
        "...ottttTTTTwgwwwwwwwTooo.",
        "...ottooooTTTgTTTooooo....",
        "....oo....oogoooo.........",
        "...........ogo............",
        "............o............."
      ],
      [
        "..............o...........",
        ".............oto..........",
        "...........ootttooo.......",
        "....o....ooTTttttTToo.....",
        "...otoo.oTTTTTTccccTTo....",
        "...otttoTTTccccttttTTGoo..",
        "...otttTTTTttttTTTTTToTTo.",
        "...otttTTTTTTTTTwwwwwwTTo.",
        "...otttTTTwwwwwwwwwwwwbbbo",
        "...ottttTTTTwgwwwwwwwTooo.",
        "...otttoooTTTgTTTooooo....",
        "...otoo...ooogooo.........",
        "....o.......ogo...........",
        ".............o............"
      ]
    ]
  },
  "PIKE": {
    "width": 28,
    "height": 14,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "t": "#287578",
      "w": "#c8e0c5",
      "S": "#f8d6a2",
      "g": "#c88b49",
      "G": "#f1ce7a",
      "l": "#76a66c",
      "L": "#c4d98b"
    },
    "frames": [
      [
        "..............o.............",
        ".............ogo............",
        "...........oogggooo.........",
        "....oo...oollgggglloo.......",
        "...ollooollllllLLLLllo......",
        "...olllllllLLLLttttllGoo....",
        "...olllllllttttllllllollo...",
        "...ollllllllllllwwwwwwllo...",
        "...ollllllwwwwwwwwwwwwbbbo..",
        "...ollllllllwgwwwwwwwSoSo...",
        "...olloooolllglllooooo.o....",
        "....oo....oogoooo...........",
        "...........ogo..............",
        "............o..............."
      ],
      [
        "..............o.............",
        ".............ogo............",
        "....o......oogggooo.........",
        "...oloo..oollgggglloo.......",
        "...ollloollllllLLLLllo......",
        "...olllllllLLLLttttllGoo....",
        "...olllllllttttllllllollo...",
        "...ollllllllllllwwwwwwllo...",
        "...ollllllwwwwwwwwwwwwbbbo..",
        "...olllollllwgwwwwwwwSoSo...",
        "...oloo.oolllglllooooo.o....",
        "....o.....ooogooo...........",
        "............ogo.............",
        ".............o.............."
      ],
      [
        "..............o.............",
        ".............ogo............",
        "...........oogggooo.........",
        "....oo...oollgggglloo.......",
        "...ollooollllllLLLLllo......",
        "...olllllllLLLLttttllGoo....",
        "...olllllllttttllllllollo...",
        "...ollllllllllllwwwwwwllo...",
        "...ollllllwwwwwwwwwwwwbbbo..",
        "...ollllllllwgwwwwwwwSoSo...",
        "...olloooolllglllooooo.o....",
        "....oo....oogoooo...........",
        "...........ogo..............",
        "............o..............."
      ],
      [
        "..............o.............",
        ".............ogo............",
        "...........oogggooo.........",
        "....o....oollgggglloo.......",
        "...oloo.ollllllLLLLllo......",
        "...olllolllLLLLttttllGoo....",
        "...olllllllttttllllllollo...",
        "...ollllllllllllwwwwwwllo...",
        "...ollllllwwwwwwwwwwwwbbbo..",
        "...ollllllllwgwwwwwwwSoSo...",
        "...olllooolllglllooooo.o....",
        "...oloo...ooogooo...........",
        "....o.......ogo.............",
        ".............o.............."
      ]
    ]
  },
  "FOX": {
    "width": 28,
    "height": 18,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "w": "#c8e0c5",
      "S": "#f8d6a2",
      "h": "#543b39",
      "H": "#aa7351",
      "g": "#c88b49"
    },
    "frames": [
      [
        "............................",
        "..................o.........",
        ".................ogo..o.....",
        ".................oggoogo....",
        "..oo.............ohgoggo....",
        ".owwo............oggggho....",
        ".owwwoo......ooooogggggo....",
        ".owwwggooooooHHHHHgggggoo...",
        "..owwggggHgggggggHggwwwggoo.",
        "..oggggggHHHHHHHHHggwwwwwgbo",
        "...ogggggHHHHHHHHHHHogwwooo.",
        "....oggggHHSSSSSSSSo.ooo....",
        ".....oogoohhSSSShhSo........",
        ".......o.ohhoooohho.........",
        "........ohhho..ohhho........",
        "........obbbo...obbbo.......",
        "........ohho....ohho........",
        ".........oo......oo........."
      ],
      [
        "............................",
        "..................o.........",
        ".................ogo..o.....",
        ".................oggoogo....",
        ".................ohgoggo....",
        "..oo.............oggggho....",
        ".owwoo.......ooooogggggo....",
        ".owwwgoooooooHHHHHgggggoo...",
        ".owwwggggHgggggggHggwwwggoo.",
        "..owwggggHHHHHHHHHggwwwwwgbo",
        "..oggggggHHHHHHHHHHHogwwooo.",
        "...ogggggHHSSSSSSSSo.ooo....",
        "....ooggoohhSSSShhSo........",
        "......oo.ohhoooohho.........",
        ".........ohho..ohho.........",
        ".........obbbo.obbbo........",
        ".........ohho..ohho.........",
        "..........oo....oo.........."
      ],
      [
        "............................",
        "..................o.........",
        ".................ogo..o.....",
        ".................oggoogo....",
        ".................ohgoggo....",
        ".................oggggho....",
        "..ooo........ooooogggggo....",
        ".owwgooooooooHHHHHgggggoo...",
        ".owwwggggHgggggggHggwwwggoo.",
        ".owwwggggHHHHHHHHHggwwwwwgbo",
        "..owwggggHHHHHHHHHHHogwwooo.",
        "..oggggggHHSSSSSSSSo.ooo....",
        "...oogggoohhSSSShhSo........",
        ".....ooo.ohhoooohho.........",
        ".........ohhhoohhho.........",
        "..........obbbobbbo.........",
        "..........ohhoohho..........",
        "...........oo..oo..........."
      ],
      [
        "............................",
        "..................o.........",
        ".................ogo..o.....",
        ".................oggoogo....",
        ".................ohgoggo....",
        "..oo.............oggggho....",
        ".owwoo.......ooooogggggo....",
        ".owwwgoooooooHHHHHgggggoo...",
        ".owwwggggHgggggggHggwwwggoo.",
        "..owwggggHHHHHHHHHggwwwwwgbo",
        "..oggggggHHHHHHHHHHHogwwooo.",
        "...ogggggHHSSSSSSSSo.ooo....",
        "....ooggoohhSSSShhSo........",
        "......oo.ohhoooohho.........",
        ".........ohho..ohho.........",
        ".........obbbo.obbbo........",
        ".........ohho..ohho.........",
        "..........oo....oo.........."
      ]
    ]
  },
  "HARE": {
    "width": 20,
    "height": 18,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "S": "#f8d6a2",
      "H": "#aa7351",
      "r": "#a34549"
    },
    "frames": [
      [
        "...............oo...",
        "............ooosso..",
        "...........oHHosso..",
        "...........oHHorso..",
        "...........oHHosso..",
        "...........oHHosso..",
        "..........osHHssso..",
        ".........oosHHssso..",
        "......oooHHsssoso...",
        "..oo.oHHHHHsssssoo..",
        ".owwossssHHsssssoSo.",
        ".owwHssssHHsssssoo..",
        ".owwHssssHHHHHHo....",
        "..oossssHHHHSSSSo...",
        "...ossssooooSSSSo...",
        "...osssso..oSSSSo...",
        "....oooo....oooo....",
        "...................."
      ],
      [
        "...............oo...",
        "............ooosso..",
        "...........oHHosso..",
        "...........oHHorso..",
        "...........oHHosso..",
        "...........oHHosso..",
        "..........osHHssso..",
        ".........oosHHssso..",
        "......oooHHsssoso...",
        "..oo.oHHHHHsssssoo..",
        ".owwossssHHsssssoSo.",
        ".owwHssssHHsssssoo..",
        ".owwHssssHHHHHHo....",
        "..oosssssHHHSSSo....",
        "...osssssoooSSSo....",
        "...ossssso.oSSSo....",
        "....ooooo...ooo.....",
        "...................."
      ],
      [
        "...............oo...",
        "............ooosso..",
        "...........oHHosso..",
        "...........oHHorso..",
        "...........oHHosso..",
        "...........oHHosso..",
        "..........osHHssso..",
        ".........oosHHssso..",
        "......oooHHsssoso...",
        "..oo.oHHHHHsssssoo..",
        ".owwossssHHsssssoSo.",
        ".owwHssssHHsssssoo..",
        ".owwHssssHHHHHHo....",
        "..oossssHHHHSSSSo...",
        "...ossssooooSSSSo...",
        "...osssso..oSSSSo...",
        "....oooo....oooo....",
        "...................."
      ],
      [
        "...............oo...",
        "............ooosso..",
        "...........oHHosso..",
        "...........oHHorso..",
        "...........oHHosso..",
        "...........oHHosso..",
        "..........osHHssso..",
        ".........oosHHssso..",
        "......oooHHsssoso...",
        "..oo.oHHHHHsssssoo..",
        ".owwossssHHsssssoSo.",
        ".owwHssssHHsssssoo..",
        ".owwHssssHHHHHHoo...",
        "..oosssHHHHHSSSSSo..",
        "...osssoooooSSSSSo..",
        "...ossso...oSSSSSo..",
        "....ooo.....ooooo...",
        "...................."
      ]
    ]
  },
  "CRAWLER": {
    "width": 28,
    "height": 16,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "w": "#c8e0c5",
      "S": "#f8d6a2",
      "v": "#655170",
      "V": "#a080a1",
      "L": "#c4d98b"
    },
    "frames": [
      [
        "............................",
        "............................",
        ".......oooooooooooo.........",
        "......ovVvvvvVvvvvVo........",
        ".....ovVwVvvVwVvvVwVoo......",
        "....ovVVVVvVVVVvVVVVvvo.....",
        "...ovvVVVVvVVVVvVVVVvvvoo...",
        "...ovvVVVVvVVVVvVVVVbbLbLo..",
        "....ovvvVVvvvVVvvvVVbbbbbo..",
        "...ovvvvvvvvvvvvvvvvbbbbbo..",
        "...ovovvvvvvvvvooovobbbbSSo.",
        "..ovo.oovoooovo..ovoooooooSo",
        ".oBo..oBo..oBo..oBo.....oSo.",
        ".oBo.oBo...oBo.oBo.......o..",
        "oBo..oBo..oBo..oBo..........",
        ".o....o....o....o..........."
      ],
      [
        "............................",
        "............................",
        ".......oooooooooooo.........",
        "......ovVvvvvVvvvvVo........",
        ".....ovVwVvvVwVvvVwVoo......",
        "....ovVVVVvVVVVvVVVVvvo.....",
        "...ovvVVVVvVVVVvVVVVvvvoo...",
        "...ovvVVVVvVVVVvVVVVbbLbLo..",
        "....ovvvVVvvvVVvvvVVbbbbbo..",
        "...ovvvvvvvvvvvvvvvvbbbbbo..",
        "...ovovvvvvvvvvoooovbbbbSSo.",
        "...ovooovooooovo.ovoooooooSo",
        "..oBo..oBo..oBo..oBo....oSo.",
        ".oBo...oBo.oBo...oBo.....o..",
        ".oBo..oBo..oBo..oBo.........",
        "..o....o....o....o.........."
      ],
      [
        "............................",
        "............................",
        ".......oooooooooooo.........",
        "......ovVvvvvVvvvvVo........",
        ".....ovVwVvvVwVvvVwVoo......",
        "....ovVVVVvVVVVvVVVVvvo.....",
        "...ovvVVVVvVVVVvVVVVvvvoo...",
        "...ovvVVVVvVVVVvVVVVbbLbLo..",
        "....ovvvVVvvvVVvvvVVbbbbbo..",
        "....ovvvvvvvvvvvvvvvbbbbbo..",
        "...ovovvvvvvvvvooooobbbbSSo.",
        "...ovoooovoooovo..ovooooooSo",
        "...oBo..oBo..oBo..oBo...oSo.",
        "...oBo.oBo...oBo.oBo.....o..",
        "..oBo..oBo..oBo..oBo........",
        "...o....o....o....o........."
      ],
      [
        "............................",
        "............................",
        ".......oooooooooooo.........",
        "......ovVvvvvVvvvvVo........",
        ".....ovVwVvvVwVvvVwVoo......",
        "....ovVVVVvVVVVvVVVVvvo.....",
        "...ovvVVVVvVVVVvVVVVvvvoo...",
        "...ovvVVVVvVVVVvVVVVbbLbLo..",
        "....ovvvVVvvvVVvvvVVbbbbbo..",
        "...ovvvvvvvvvvvvvvvvbbbbbo..",
        "...ovovvvvvvvvvoooovbbbbSSo.",
        "...ovooovooooovo.ovoooooooSo",
        "..oBo..oBo..oBo..oBo....oSo.",
        ".oBo...oBo.oBo...oBo.....o..",
        ".oBo..oBo..oBo..oBo.........",
        "..o....o....o....o.........."
      ]
    ]
  },
  "MOLE": {
    "width": 24,
    "height": 18,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "s": "#dba67d",
      "S": "#f8d6a2",
      "h": "#543b39",
      "H": "#aa7351",
      "r": "#a34549"
    },
    "frames": [
      [
        "........................",
        "........................",
        "........................",
        "..........ooooo.........",
        "......oooohhhhhoo.......",
        ".....ohhhhHHHhhhhoo.....",
        "....ohhHHHHHHHHHhhho....",
        "...ohhHHHHHHHHHHHhhho...",
        "...ohhhHHHHHHHHHsssoso..",
        "...ohhhhhhhhhhhhsssssoo.",
        "...ohhhhhhhhhhhhsssssoro",
        "....ohhhhhhhhhhhsssssoo.",
        "....ohhsssshhhhhsssso...",
        ".....oossssooooosssso...",
        "......osssso...osssso...",
        "......oSoSo....oSoSo....",
        ".......o.o......o.o.....",
        "........................"
      ],
      [
        "........................",
        "........................",
        "........................",
        "..........ooooo.........",
        "......oooohhhhhoo.......",
        ".....ohhhhHHHhhhhoo.....",
        "....ohhHHHHHHHHHhhho....",
        "...ohhHHHHHHHHHHHhhho...",
        "...ohhhHHHHHHHHHsssoso..",
        "...ohhhhhhhhhhhhsssssoo.",
        "...ohhhhhhhhhhhhsssssoro",
        "....ohhhhhhhhhhhsssssoo.",
        "....ohhhsssshhhssssoo...",
        ".....ooossssooosssso....",
        ".......osssso.osssso....",
        ".......oSoSo..oSoSo.....",
        "........o.o....o.o......",
        "........................"
      ],
      [
        "........................",
        "........................",
        "........................",
        "..........ooooo.........",
        "......oooohhhhhoo.......",
        ".....ohhhhHHHhhhhoo.....",
        "....ohhHHHHHHHHHhhho....",
        "...ohhHHHHHHHHHHHhhho...",
        "...ohhhHHHHHHHHHsssoso..",
        "...ohhhhhhhhhhhhsssssoo.",
        "...ohhhhhhhhhhhhsssssoro",
        "....ohhhhhhhhhhhsssssoo.",
        "....ohhsssshhhhhsssso...",
        ".....oossssooooosssso...",
        "......osssso...osssso...",
        "......oSoSo....oSoSo....",
        ".......o.o......o.o.....",
        "........................"
      ],
      [
        "........................",
        "........................",
        "........................",
        "..........ooooo.........",
        "......oooohhhhhoo.......",
        ".....ohhhhHHHhhhhoo.....",
        "....ohhHHHHHHHHHhhho....",
        "...ohhHHHHHHHHHHHhhho...",
        "...ohhhHHHHHHHHHsssoso..",
        "...ohhhhhhhhhhhhsssssoo.",
        "...ohhhhhhhhhhhhsssssoro",
        "....ohhhhhhhhhhhsssssoo.",
        "....ohsssshhhhhhhsssso..",
        ".....ossssooooooosssso..",
        ".....osssso.....osssso..",
        ".....oSoSo......oSoSo...",
        "......o.o........o.o....",
        "........................"
      ]
    ]
  },
  "BIRD": {
    "width": 24,
    "height": 18,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "B": "#476171",
      "t": "#287578",
      "g": "#c88b49",
      "G": "#f1ce7a",
      "c": "#74c9d0"
    },
    "frames": [
      [
        "........................",
        ".....oo.................",
        "....occoo...............",
        ".....oBccoo.............",
        "......oBBcco............",
        "......oBBBBo.ooooo......",
        ".......oBBBBoccccco.....",
        "......ooBBBBBcccocoo....",
        ".....otttttBBcccccGGo...",
        "....ootttttttcccccooGo..",
        "..ooBBBBtttttttooo..o...",
        ".oBBBBBBtttttto.........",
        ".oBBBooooogooo..........",
        "..ooo.....ogo...........",
        "...........o............",
        "........................",
        "........................",
        "........................"
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "...o....................",
        "..ocoo.......ooooo......",
        "...ocBoo.ooooccccco.....",
        "....occBottttcccocoo....",
        ".....otcBBtttcccccGGo...",
        "....oottcttBtcccccooGo..",
        "..ooBBBBtttttttooo..o...",
        ".oBBBBBBtttttto.........",
        ".oBBBooooogooo..........",
        "..ooo.....ogo...........",
        "...........o............",
        "........................",
        "........................",
        "........................"
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".............ooooo......",
        ".........ooooccccco.....",
        "......ooottttcccocoo....",
        ".....otttttttcccccGGo...",
        "....oottBBBBBcccccooGo..",
        "..ooBBBBBBBBBttooo..o...",
        ".oBBBBBBBBBBBto.........",
        ".oBBBoooBBgBco..........",
        "..ooo..oBBcgo...........",
        ".......occoo............",
        "......ocoo..............",
        ".......o................",
        "........................"
      ],
      [
        "........................",
        "........................",
        "........................",
        "........................",
        "....oooo................",
        "...occcBooo..ooooo......",
        "....ooBccccooccccco.....",
        "......ooBBBBtcccocoo....",
        ".....otttttBBcccccGGo...",
        "....ootttttttcccccooGo..",
        "..ooBBBBtttttttooo..o...",
        ".oBBBBBBtttttto.........",
        ".oBBBooooogooo..........",
        "..ooo.....ogo...........",
        "...........o............",
        "........................",
        "........................",
        "........................"
      ]
    ]
  },
  "DYNAMITEER": {
    "width": 32,
    "height": 16,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "S": "#f8d6a2",
      "h": "#543b39",
      "g": "#c88b49",
      "G": "#f1ce7a",
      "C": "#d0f2df",
      "r": "#a34549",
      "R": "#eb8060"
    },
    "frames": [
      [
        "..........ooooooo...............",
        "........orRRRRRRRro.............",
        "........orrrrrrrrro.............",
        ".......orrrrbCCCCCbo............",
        ".......ooBBBhhhhsoo.............",
        "...oooorrBBBhhhhhro...o.........",
        "..oRRhhrgRRrrrrrrrroooGo........",
        "..oRRhhrRRgbbbbbbrrrrrrro.......",
        "..oRRhgggRRggbbbbrrrrrrro.......",
        "..oRRhgggRRrrrgrrrBBBrrro.......",
        "..ohhhgggrrrrrrrgrboorrro.......",
        "...ooooorhhhGGhhhhbo.ooo........",
        ".......oBBBoooooBBo.............",
        "......owbbbbo..owbbbbo..........",
        "......obbbbbo..obbbbbo..........",
        "................................"
      ],
      [
        "..........ooooooo...............",
        "........orRRRRRRRro.............",
        "........orrrrrrrrro.............",
        ".......orrrrbCCCCCbo............",
        ".......ooBBBhhhhsoo.............",
        "...oooorrBBBhhhhhro...o.........",
        "..oRRhhrgRRrrrrrrrroooGo........",
        "..oRRhhrRRgbbbbbbrrrrrrro.......",
        "..oRRhgggRRggbbbbrrrrrrro.......",
        "..oRRhgggRRrrrgrrrBBBrrro.......",
        "..ohhhgggrrrrrrrgrboorrro.......",
        "...ooooorhhhGGhhhhbo.ooo........",
        "........oBBoooooBBo.............",
        ".......owbbbboowbbbbo...........",
        ".......obbbbboobbbbbo...........",
        "................................"
      ],
      [
        "..........ooooooo...............",
        "........orRRRRRRRro.............",
        "........orrrrrrrrro.............",
        ".......orrrrbCCCCCbo............",
        ".......ooBBBhhhhsoo.............",
        "...oooorrBBBhhhhhro...o.........",
        "..oRRhhrgRRrrrrrrrroooGo........",
        "..oRRhhrRRgbbbbbbrrrrrrro.......",
        "..oRRhgggRRggbbbbrrrrrrro.......",
        "..oRRhgggRRrrrgrrrBBBrrro.......",
        "..ohhhgggrrrrrrrgrboorrro.......",
        "...ooooorhhhGGhhhhbo.ooo........",
        "........oBBooooBBBo.............",
        "........owbbbbwbbbbo............",
        "........obbbbbbbbbbo............",
        "................................"
      ],
      [
        "..........ooooooo...............",
        "........orRRRRRRRro.............",
        "........orrrrrrrrro.............",
        ".......orrrrbCCCCCbo............",
        ".......ooBBBhhhhsoo.............",
        "...oooorrBBBhhhhhro...o.........",
        "..oRRhhrgRRrrrrrrrroooGo........",
        "..oRRhhrRRgbbbbbbrrrrrrro.......",
        "..oRRhgggRRggbbbbrrrrrrro.......",
        "..oRRhgggRRrrrgrrrBBBrrro.......",
        "..ohhhgggrrrrrrrgrboorrro.......",
        "...ooooorhhhGGhhhhbo.ooo........",
        "........oBBoooooBBo.............",
        ".......owbbbboowbbbbo...........",
        ".......obbbbboobbbbbo...........",
        "................................"
      ]
    ]
  },
  "BORE_SENTINEL": {
    "width": 32,
    "height": 18,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "S": "#f8d6a2",
      "h": "#543b39",
      "g": "#c88b49",
      "G": "#f1ce7a",
      "c": "#74c9d0",
      "C": "#d0f2df"
    },
    "frames": [
      [
        "..........ooooooo...............",
        ".........ogggggggo..............",
        "........ogggggggggo.............",
        ".......ogggggggggggo............",
        "........oBBBbbbbbbbo............",
        ".......ooBBBhhhhsoo.............",
        "...oooogGGGggggggggo............",
        "..occbbgGGGggggggggoooooooo.....",
        "..occbbgGGGbbbbbbggBBBBBBgGggo..",
        "..occbbgGGGbbbbbbggBBBBBBgGgSgo.",
        "..obbbbgGGGgggggggBBBBBBBgoo....",
        "..obbbbgGGGgggggggBBBBoooo......",
        "...oooooghhhGGhhhhbo............",
        ".......obhhhGGhhhhbo............",
        ".......oBBoo...oBBooo...........",
        "......owbbbbo..owbbbbo..........",
        ".......ooooo....ooooo...........",
        "................................"
      ],
      [
        "..........ooooooo...............",
        ".........ogggggggo..............",
        "........ogggggggggo.............",
        ".......ogggggggggggo............",
        "........oBBBbbbbbbbo............",
        ".......ooBBBhhhhsoo.............",
        "...oooogGGGggggggggo............",
        "..occbbgGGGggggggggoooooooo.....",
        "..occbbgGGGbbbbbbggBBBBBBgGggo..",
        "..occbbgGGGbbbbbbggBBBBBBgGgSgo.",
        "..obbbbgGGGgggggggBBBBBBBgoo....",
        "..obbbbgGGGgggggggBBBBoooo......",
        "...oooooghhhGGhhhhbo............",
        ".......obhhhGGhhhhbo............",
        ".......oBBBoo.oBBBoo............",
        ".......owbbbboowbbbbo...........",
        "........ooooo..ooooo............",
        "................................"
      ],
      [
        "..........ooooooo...............",
        ".........ogggggggo..............",
        "........ogggggggggo.............",
        ".......ogggggggggggo............",
        "........oBBBbbbbbbbo............",
        ".......ooBBBhhhhsoo.............",
        "...oooogGGGggggggggo............",
        "..occbbgGGGggggggggoooooooo.....",
        "..occbbgGGGbbbbbbggBBBBBBgGggo..",
        "..occbbgGGGbbbbbbggBBBBBBgGgSgo.",
        "..obbbbgGGGgggggggBBBBBBBgoo....",
        "..obbbbgGGGgggggggBBBBoooo......",
        "...oooooghhhGGhhhhbo............",
        ".......obhhhGGhhhhbo............",
        "........oBBooooBBoo.............",
        "........owbbbbwbbbbo............",
        ".........oooooooooo.............",
        "................................"
      ],
      [
        "..........ooooooo...............",
        ".........ogggggggo..............",
        "........ogggggggggo.............",
        ".......ogggggggggggo............",
        "........oBBBbbbbbbbo............",
        ".......ooBBBhhhhsoo.............",
        "...oooogGGGggggggggo............",
        "..occbbgGGGggggggggoooooooo.....",
        "..occbbgGGGbbbbbbggBBBBBBgGggo..",
        "..occbbgGGGbbbbbbggBBBBBBgGgSgo.",
        "..obbbbgGGGgggggggBBBBBBBgoo....",
        "..obbbbgGGGgggggggBBBBoooo......",
        "...oooooghhhGGhhhhbo............",
        ".......obhhhGGhhhhbo............",
        ".......oBBBoo.oBBBoo............",
        ".......owbbbboowbbbbo...........",
        "........ooooo..ooooo............",
        "................................"
      ]
    ]
  },
  "CAUSTIC_MORTARMAN": {
    "width": 32,
    "height": 18,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "t": "#287578",
      "T": "#4eaaa0",
      "w": "#c8e0c5",
      "h": "#543b39",
      "G": "#f1ce7a",
      "C": "#d0f2df",
      "l": "#76a66c",
      "L": "#c4d98b"
    },
    "frames": [
      [
        "..........ooooooo...............",
        ".........ottttttto..............",
        "........ottttttttto.............",
        ".......ottttttttttto............",
        "...oooo.oBBBbbbbbbbo...oooo.....",
        "..oBBBBooBBBBLBBBBo...oLLLBo....",
        "..olLLBtTTTttttttttoooBBBBBo....",
        "..olllBtTTTtttttttttttBBBBo.....",
        "..olllBtTTTbbbbbbtttBBBBBo......",
        "..olllBtTTTbbbbbbtttBBBBo.......",
        "..oBBBBtTTTtttttttttttto........",
        "..oBBBBtTTTtttttttttttto........",
        "...ooooothhhGGhhhhbo............",
        ".......obhhhGGhhhhbo............",
        ".......oBBoo...oBBooo...........",
        "......owbbbbo..owbbbbo..........",
        ".......ooooo....ooooo...........",
        "................................"
      ],
      [
        "..........ooooooo...............",
        ".........ottttttto..............",
        "........ottttttttto.............",
        ".......ottttttttttto............",
        "...oooo.oBBBbbbbbbbo...oooo.....",
        "..oBBBBooBBBBLBBBBo...oLLLBo....",
        "..olLLBtTTTttttttttoooBBBBBo....",
        "..olllBtTTTtttttttttttBBBBo.....",
        "..olllBtTTTbbbbbbtttBBBBBo......",
        "..olllBtTTTbbbbbbtttBBBBo.......",
        "..oBBBBtTTTtttttttttttto........",
        "..oBBBBtTTTtttttttttttto........",
        "...ooooothhhGGhhhhbo............",
        ".......obhhhGGhhhhbo............",
        ".......oBBBoo.oBBBoo............",
        ".......owbbbboowbbbbo...........",
        "........ooooo..ooooo............",
        "................................"
      ],
      [
        "..........ooooooo...............",
        ".........ottttttto..............",
        "........ottttttttto.............",
        ".......ottttttttttto............",
        "...oooo.oBBBbbbbbbbo...oooo.....",
        "..oBBBBooBBBBLBBBBo...oLLLBo....",
        "..olLLBtTTTttttttttoooBBBBBo....",
        "..olllBtTTTtttttttttttBBBBo.....",
        "..olllBtTTTbbbbbbtttBBBBBo......",
        "..olllBtTTTbbbbbbtttBBBBo.......",
        "..oBBBBtTTTtttttttttttto........",
        "..oBBBBtTTTtttttttttttto........",
        "...ooooothhhGGhhhhbo............",
        ".......obhhhGGhhhhbo............",
        "........oBBooooBBoo.............",
        "........owbbbbwbbbbo............",
        ".........oooooooooo.............",
        "................................"
      ],
      [
        "..........ooooooo...............",
        ".........ottttttto..............",
        "........ottttttttto.............",
        ".......ottttttttttto............",
        "...oooo.oBBBbbbbbbbo...oooo.....",
        "..oBBBBooBBBBLBBBBo...oLLLBo....",
        "..olLLBtTTTttttttttoooBBBBBo....",
        "..olllBtTTTtttttttttttBBBBo.....",
        "..olllBtTTTbbbbbbtttBBBBBo......",
        "..olllBtTTTbbbbbbtttBBBBo.......",
        "..oBBBBtTTTtttttttttttto........",
        "..oBBBBtTTTtttttttttttto........",
        "...ooooothhhGGhhhhbo............",
        ".......obhhhGGhhhhbo............",
        ".......oBBBoo.oBBBoo............",
        ".......owbbbboowbbbbo...........",
        "........ooooo..ooooo............",
        "................................"
      ]
    ]
  },
  "CLUSTER_WASP": {
    "width": 28,
    "height": 20,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "w": "#c8e0c5",
      "S": "#f8d6a2",
      "H": "#aa7351",
      "g": "#c88b49",
      "c": "#74c9d0",
      "R": "#eb8060",
      "v": "#655170"
    },
    "frames": [
      [
        ".....ooccco.....owwoo.......",
        "....occccco.....owwwwo......",
        "....occcccco...owwwwwwo.....",
        ".....occccco...owwwwwo......",
        "......occccco.owwwwwwo......",
        "......occccco.owwwwwo.......",
        ".......occcccowwwwwo........",
        "........occccowwwwo.........",
        "......oogggggowwwwoooo......",
        ".....oggbbgggggggHHHRHo.....",
        "....ogggbbgggbbggHHHHHo.....",
        "....ogggbbgggbbggHHHHHo.....",
        ".....oggbbgggbbggHHHHSSoo...",
        "......ogbbgggbbggggooooSSo..",
        ".......obbgggbbggoo....oo...",
        ".......ovooooovoo...........",
        "......ovo.....ovo...........",
        ".....ovo.......ovo..........",
        "......o.........o...........",
        "............................"
      ],
      [
        ".......ooo.......oo.........",
        ".....ooccco.....owwoo.......",
        "....occccco.....owwwwo......",
        ".....occccco...owwwwwwo.....",
        ".....occcccco.owwwwwwo......",
        "......occccco.owwwwwo.......",
        ".......occcccowwwwwwo.......",
        ".......occcccowwwwwo........",
        "......oogggggowwwwoooo......",
        ".....oggbbgggggggHHHRHo.....",
        "....ogggbbgggbbggHHHHHo.....",
        "....ogggbbgggbbggHHHHHo.....",
        ".....oggbbgggbbggHHHHSSoo...",
        "......ogbbgggbbggggooooSSo..",
        ".......obbgggbbggoo....oo...",
        ".......ovooooovoo...........",
        "......ovo.....ovo...........",
        ".....ovo.......ovo..........",
        "......o.........o...........",
        "............................"
      ],
      [
        "............................",
        "............................",
        "............................",
        ".......ooo.......oo.........",
        ".....ooccco.....owwoo.......",
        "....occcccco...owwwwwo......",
        ".....occcccco.owwwwwwwo.....",
        "......oocccccowwwwwwoo......",
        "......oogggggowwwwwooo......",
        ".....oggbbgggggggHHHRHo.....",
        "....ogggbbgggbbggHHHHHo.....",
        "....ogggbbgggbbggHHHHHo.....",
        ".....oggbbgggbbggHHHHSSoo...",
        "......ogbbgggbbggggooooSSo..",
        ".......obbgggbbggoo....oo...",
        ".......ovooooovoo...........",
        "......ovo.....ovo...........",
        ".....ovo.......ovo..........",
        "......o.........o...........",
        "............................"
      ],
      [
        "............................",
        ".......ooo.......oo.........",
        ".....ooccco.....owwoo.......",
        "....occcccco...owwwwwo......",
        ".....occccco...owwwwwwo.....",
        "......occccco.owwwwwwo......",
        "......occccccowwwwwwo.......",
        ".......occcccowwwwwo........",
        "......oogggggowwwwoooo......",
        ".....oggbbgggggggHHHRHo.....",
        "....ogggbbgggbbggHHHHHo.....",
        "....ogggbbgggbbggHHHHHo.....",
        ".....oggbbgggbbggHHHHSSoo...",
        "......ogbbgggbbggggooooSSo..",
        ".......obbgggbbggoo....oo...",
        ".......ovooooovoo...........",
        "......ovo.....ovo...........",
        ".....ovo.......ovo..........",
        "......o.........o...........",
        "............................"
      ]
    ]
  },
  "MINIGUNNER": {
    "width": 34,
    "height": 18,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "h": "#543b39",
      "g": "#c88b49",
      "G": "#f1ce7a",
      "c": "#74c9d0",
      "C": "#d0f2df"
    },
    "frames": [
      [
        "..........ooooooo.................",
        ".........oBBBBBBBo................",
        "........oBBBBBBBBBo...............",
        ".......oBBBBBBBBBBBo..............",
        "........oBBBbbbbbbbo..............",
        "..oooooooBBBhhhhsoo...............",
        ".ohggghBcccBBBBBBBBo..............",
        ".ohggghBcccBBBBBBBBoo.............",
        ".ohggghBcccbbbbbbBBBBoBccccccbbo..",
        ".ohggghBcccbbbbbbbbbbbBBBBBBBbbo..",
        ".ohggghBcccBBBBBBbbbbbBwwwwwwbbo..",
        ".ohhhhhBcccBBBBBBbbbbbBBBBBBBbbo..",
        ".ohhhhhoBhhhGGhhhhboo.............",
        "..oooooobhhhGGhhhhbo..............",
        ".......oBBoo...oBBooo.............",
        "......owbbbbo..owbbbbo............",
        ".......ooooo....ooooo.............",
        ".................................."
      ],
      [
        "..........ooooooo.................",
        ".........oBBBBBBBo................",
        "........oBBBBBBBBBo...............",
        ".......oBBBBBBBBBBBo..............",
        "........oBBBbbbbbbbo..............",
        "..oooooooBBBhhhhsoo...............",
        ".ohggghBcccBBBBBBBBo..............",
        ".ohggghBcccBBBBBBBBoo.............",
        ".ohggghBcccbbbbbbBBBBoBccccccbbo..",
        ".ohggghBcccbbbbbbbbbbbBBBBBBBbbo..",
        ".ohggghBcccBBBBBBbbbbbBwwwwwwbbo..",
        ".ohhhhhBcccBBBBBBbbbbbBBBBBBBbbo..",
        ".ohhhhhoBhhhGGhhhhboo.............",
        "..oooooobhhhGGhhhhbo..............",
        ".......oBBBoo.oBBBoo..............",
        ".......owbbbboowbbbbo.............",
        "........ooooo..ooooo..............",
        ".................................."
      ],
      [
        "..........ooooooo.................",
        ".........oBBBBBBBo................",
        "........oBBBBBBBBBo...............",
        ".......oBBBBBBBBBBBo..............",
        "........oBBBbbbbbbbo..............",
        "..oooooooBBBhhhhsoo...............",
        ".ohggghBcccBBBBBBBBo..............",
        ".ohggghBcccBBBBBBBBoo.............",
        ".ohggghBcccbbbbbbBBBBoBccccccbbo..",
        ".ohggghBcccbbbbbbbbbbbBBBBBBBbbo..",
        ".ohggghBcccBBBBBBbbbbbBwwwwwwbbo..",
        ".ohhhhhBcccBBBBBBbbbbbBBBBBBBbbo..",
        ".ohhhhhoBhhhGGhhhhboo.............",
        "..oooooobhhhGGhhhhbo..............",
        "........oBBooooBBoo...............",
        "........owbbbbwbbbbo..............",
        ".........oooooooooo...............",
        ".................................."
      ],
      [
        "..........ooooooo.................",
        ".........oBBBBBBBo................",
        "........oBBBBBBBBBo...............",
        ".......oBBBBBBBBBBBo..............",
        "........oBBBbbbbbbbo..............",
        "..oooooooBBBhhhhsoo...............",
        ".ohggghBcccBBBBBBBBo..............",
        ".ohggghBcccBBBBBBBBoo.............",
        ".ohggghBcccbbbbbbBBBBoBccccccbbo..",
        ".ohggghBcccbbbbbbbbbbbBBBBBBBbbo..",
        ".ohggghBcccBBBBBBbbbbbBwwwwwwbbo..",
        ".ohhhhhBcccBBBBBBbbbbbBBBBBBBbbo..",
        ".ohhhhhoBhhhGGhhhhboo.............",
        "..oooooobhhhGGhhhhbo..............",
        ".......oBBBoo.oBBBoo..............",
        ".......owbbbboowbbbbo.............",
        "........ooooo..ooooo..............",
        ".................................."
      ]
    ]
  },
  "SURVEYOR": {
    "width": 16,
    "height": 22,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "t": "#287578",
      "T": "#4eaaa0",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "S": "#f8d6a2",
      "h": "#543b39",
      "H": "#aa7351",
      "g": "#c88b49",
      "G": "#f1ce7a",
      "c": "#74c9d0",
      "C": "#d0f2df"
    },
    "frames": [
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        ".gggGotto.......",
        "...ootTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....ob..bo......",
        "...obB..Bbo.....",
        "...ob....bo.....",
        "..ob......bo....",
        "..oo......oo....",
        ".ooo......ooo..."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        "....ootto.......",
        ".gggGtTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....obBBbo......",
        ".....obbo.......",
        ".....obBo.......",
        ".....oBbo.......",
        ".....obbo.......",
        ".....oooo......."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        ".gggGotto.......",
        "...ootTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....ob..bo......",
        "....oB..Bo......",
        ".....boob.......",
        "....ob..bo......",
        "...ob....bo.....",
        "...ooo...ooo...."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        "....ootto.......",
        ".gggGtTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....obBBbo......",
        ".....obbo.......",
        ".....obBo.......",
        ".....oBbo.......",
        ".....obbo.......",
        ".....oooo......."
      ]
    ]
  },
  "SHIELD_ANCHOR": {
    "width": 26,
    "height": 27,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "t": "#287578",
      "T": "#4eaaa0",
      "w": "#c8e0c5",
      "g": "#c88b49",
      "c": "#74c9d0",
      "C": "#d0f2df"
    },
    "frames": [
      [
        "..........................",
        "............o.............",
        "...........oto............",
        "..........otcto...........",
        "........ootccctoo.........",
        ".......otttcccctto........",
        "......otttcccccttto.......",
        ".....otttcccccccttto......",
        "..ooootttccccccctttoooo...",
        ".oBTBotttccccccctttoBBBo..",
        ".oBTBotttcccccctttooBBBo..",
        ".oBTBottttccccctttooBBBo..",
        ".oBTBoottttcccttttooBTBo..",
        ".oBTBo.otttcctttto.oBTBo..",
        ".oBBBo..otttctttto.oBTBo..",
        ".oBBBo...otttttto..oBTBo..",
        ".oBBBoooooBttttoooooBTBo..",
        "..ooooggggBBtBBogggoooo...",
        ".....oggggBBBBBogggo......",
        ".....oggggBBBBBogggo......",
        ".....oggggBBBBBogggo......",
        ".....oocccBBBBBcccoo......",
        "....obbBBBBBBBBBBBbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        ".....ooooooooooooooo......",
        ".........................."
      ],
      [
        "..........................",
        "............o.............",
        "...........oto............",
        "..........otcto...........",
        "........ootcCctoo.........",
        ".......otttcCcctto........",
        "......otttccCccttto.......",
        ".....otttcccCcccttto......",
        "..ooootttcccCccctttoooo...",
        ".oBTBotttcccCccctttoBBBo..",
        ".oBTBotttcccCcctttooBBBo..",
        ".oBTBottttccCcctttooBBBo..",
        ".oBTBoottttcCcttttooBTBo..",
        ".oBTBo.otttcCtttto.oBTBo..",
        ".oBBBo..otttctttto.oBTBo..",
        ".oBBBo...otttttto..oBTBo..",
        ".oBBBoooooBttttoooooBTBo..",
        "..ooooggggBBtBBogggoooo...",
        ".....oggggBBBBBogggo......",
        ".....oggggBBBBBogggo......",
        ".....oggggBBBBBogggo......",
        ".....oocccBBBBBcccoo......",
        "....obbBBBBBBBBBBBbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        ".....ooooooooooooooo......",
        ".........................."
      ],
      [
        "..........................",
        "............o.............",
        "...........oto............",
        "..........otcto...........",
        "........ootcwctoo.........",
        ".......otttcwcctto........",
        "......otttccwccttto.......",
        ".....otttcccwcccttto......",
        "..ooootttcccwccctttoooo...",
        ".oBTBotttcccwccctttoBBBo..",
        ".oBTBotttcccwcctttooBBBo..",
        ".oBTBottttccwcctttooBBBo..",
        ".oBTBoottttcwcttttooBTBo..",
        ".oBTBo.otttcwtttto.oBTBo..",
        ".oBBBo..otttctttto.oBTBo..",
        ".oBBBo...otttttto..oBTBo..",
        ".oBBBoooooBttttoooooBTBo..",
        "..ooooggggBBtBBogggoooo...",
        ".....oggggBBBBBogggo......",
        ".....oggggBBBBBogggo......",
        ".....oggggBBBBBogggo......",
        ".....oocccBBBBBcccoo......",
        "....obbBBBBBBBBBBBbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        ".....ooooooooooooooo......",
        ".........................."
      ],
      [
        "..........................",
        "............o.............",
        "...........oto............",
        "..........otcto...........",
        "........ootcCctoo.........",
        ".......otttcCcctto........",
        "......otttccCccttto.......",
        ".....otttcccCcccttto......",
        "..ooootttcccCccctttoooo...",
        ".oBTBotttcccCccctttoBBBo..",
        ".oBTBotttcccCcctttooBBBo..",
        ".oBTBottttccCcctttooBBBo..",
        ".oBTBoottttcCcttttooBTBo..",
        ".oBTBo.otttcCtttto.oBTBo..",
        ".oBBBo..otttctttto.oBTBo..",
        ".oBBBo...otttttto..oBTBo..",
        ".oBBBoooooBttttoooooBTBo..",
        "..ooooggggBBtBBogggoooo...",
        ".....oggggBBBBBogggo......",
        ".....oggggBBBBBogggo......",
        ".....oggggBBBBBogggo......",
        ".....oocccBBBBBcccoo......",
        "....obbBBBBBBBBBBBbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        ".....ooooooooooooooo......",
        ".........................."
      ]
    ]
  },
  "QUARRY_FOREMAN": {
    "width": 36,
    "height": 20,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "h": "#543b39",
      "g": "#c88b49",
      "G": "#f1ce7a",
      "c": "#74c9d0",
      "C": "#d0f2df",
      "R": "#eb8060"
    },
    "frames": [
      [
        "..........ooooooo...................",
        ".........ogggggggo..................",
        "........ogggggggggo.................",
        ".......ogggggggggggo................",
        ".......oggggbCCCCCbo................",
        ".oBGGGGBoBBBhhhhsoGGGGGGo...........",
        ".oBGGGGBgBBBhhhhhgggggggo...........",
        ".oBBBBBBGGGgggggggggggggo...........",
        ".oBBcBBBGGGGGGGGGgggggggo.oo........",
        ".oBBcBBBGGGRRRRRbggggoooooggoo......",
        "..oocBBBGGGRRRRRbgggBBBBBBgGggoo....",
        "...ocBBBGGGbbbbbbgBBBBBBBBgGggggo...",
        "...ocBBBGGGgggggggBBBBBBBBgGggoo....",
        "...oBBBBggggggggggboBBBBBBggoo......",
        "...oBBBBghhhGGhhhhbooooooooo........",
        ".......oBBBoooooBBo.................",
        ".......oBBoo...oBBooo...............",
        "......owbbbbo..owbbbbo..............",
        ".......ooooo....ooooo...............",
        "...................................."
      ],
      [
        "..........ooooooo...................",
        ".........ogggggggo..................",
        "........ogggggggggo.................",
        ".......ogggggggggggo................",
        ".......oggggbCCCCCbo................",
        ".oBGGGGBoBBBhhhhsoGGGGGGo...........",
        ".oBGGGGBgBBBhhhhhgggggggo...........",
        ".oBBBBBBGGGgggggggggggggo...........",
        ".oBBcBBBGGGGGGGGGgggggggo.oo........",
        ".oBBcBBBGGGRRRRRbggggoooooggoo......",
        "..oocBBBGGGRRRRRbgggBBBBBBgGggoo....",
        "...ocBBBGGGbbbbbbgBBBBBBBBgGggggo...",
        "...ocBBBGGGgggggggBBBBBBBBgGggoo....",
        "...oBBBBggggggggggboBBBBBBggoo......",
        "...oBBBBghhhGGhhhhbooooooooo........",
        "........oBBoooooBBo.................",
        ".......oBBBoo.oBBBoo................",
        ".......owbbbboowbbbbo...............",
        "........ooooo..ooooo................",
        "...................................."
      ],
      [
        "..........ooooooo...................",
        ".........ogggggggo..................",
        "........ogggggggggo.................",
        ".......ogggggggggggo................",
        ".......oggggbCCCCCbo................",
        ".oBGGGGBoBBBhhhhsoGGGGGGo...........",
        ".oBGGGGBgBBBhhhhhgggggggo...........",
        ".oBBBBBBGGGgggggggggggggo...........",
        ".oBBcBBBGGGGGGGGGgggggggo.oo........",
        ".oBBcBBBGGGRRRRRbggggoooooggoo......",
        "..oocBBBGGGRRRRRbgggBBBBBBgGggoo....",
        "...ocBBBGGGbbbbbbgBBBBBBBBgGggggo...",
        "...ocBBBGGGgggggggBBBBBBBBgGggoo....",
        "...oBBBBggggggggggboBBBBBBggoo......",
        "...oBBBBghhhGGhhhhbooooooooo........",
        "........oBBooooBBBo.................",
        "........oBBooooBBoo.................",
        "........owbbbbwbbbbo................",
        ".........oooooooooo.................",
        "...................................."
      ],
      [
        "..........ooooooo...................",
        ".........ogggggggo..................",
        "........ogggggggggo.................",
        ".......ogggggggggggo................",
        ".......oggggbCCCCCbo................",
        ".oBGGGGBoBBBhhhhsoGGGGGGo...........",
        ".oBGGGGBgBBBhhhhhgggggggo...........",
        ".oBBBBBBGGGgggggggggggggo...........",
        ".oBBcBBBGGGGGGGGGgggggggo.oo........",
        ".oBBcBBBGGGRRRRRbggggoooooggoo......",
        "..oocBBBGGGRRRRRbgggBBBBBBgGggoo....",
        "...ocBBBGGGbbbbbbgBBBBBBBBgGggggo...",
        "...ocBBBGGGgggggggBBBBBBBBgGggoo....",
        "...oBBBBggggggggggboBBBBBBggoo......",
        "...oBBBBghhhGGhhhhbooooooooo........",
        "........oBBoooooBBo.................",
        ".......oBBBoo.oBBBoo................",
        ".......owbbbboowbbbbo...............",
        "........ooooo..ooooo................",
        "...................................."
      ]
    ]
  },
  "REACTOR_WARDEN": {
    "width": 34,
    "height": 22,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "S": "#f8d6a2",
      "h": "#543b39",
      "G": "#f1ce7a",
      "c": "#74c9d0",
      "r": "#a34549",
      "R": "#eb8060",
      "v": "#655170",
      "V": "#a080a1"
    },
    "frames": [
      [
        "..........ooooooo.................",
        ".........ovvvvvvvo................",
        "........ovVVVVVVVvo...............",
        "..ovoo.ovvvvvvvvvvvo.ooVVo........",
        "..ovvvoovvvvbRRRRRbooVVVVo........",
        "..ovRvvvoBBBbbbbbbbVVVRVVo........",
        "..ovvRvvvBBBhhhhsooVVVRVVo........",
        "..ovvvRvvBBBhhhhhvoVVVVRVo........",
        "...oovvvvVVvvvvvvvvoVVVVVo........",
        "..oBBBBBvVVrrrrrVvvvVVVoo.........",
        "..oBBBBBVVVrRSRrbvvvVoooo.........",
        "..oBBBBBVVVrRRRrbvvBBBBBBooooooo..",
        "..oBBBBBVVVrRRRrbvBBBBBBvVVVVVVvo.",
        "..oBBBBBVVVrrrrrvvBBBBBBvvvvvvvvo.",
        "..oBBBBBvvvvvvvvvvbBBBBBvvvvvvvvo.",
        "..oBBBBBvhccccccchbBBBBBBooooooo..",
        "...ooooobhhhGGhhhhboooooo.........",
        ".......oBBBoooooBBo...............",
        ".......oBBoo...oBBooo.............",
        "......obbbbbo..obbbbbo............",
        ".......ooooo....ooooo.............",
        ".................................."
      ],
      [
        "..........ooooooo.................",
        ".........ovvvvvvvo................",
        "........ovVVVVVVVvo...............",
        "..ovoo.ovvvvvvvvvvvo.ooVVo........",
        "..ovvvoovvvvbRRRRRbooVVVVo........",
        "..ovRvvvoBBBbbbbbbbVVVRVVo........",
        "..ovvRvvvBBBhhhhsooVVVRVVo........",
        "..ovvvRvvBBBhhhhhvoVVVVRVo........",
        "...oovvvvVVvvvvvvvvoVVVVVo........",
        "..oBBBBBvVVrrrrrVvvvVVVoo.........",
        "..oBBBBBVVVrRSRrbvvvVoooo.........",
        "..oBBBBBVVVrRRRrbvvBBBBBBooooooo..",
        "..oBBBBBVVVrRRRrbvBBBBBBvVVVVVVvo.",
        "..oBBBBBVVVrrrrrvvBBBBBBvvvvvvvvo.",
        "..oBBBBBvvvvvvvvvvbBBBBBvvvvvvvvo.",
        "..oBBBBBvhccccccchbBBBBBBooooooo..",
        "...ooooobhhhGGhhhhboooooo.........",
        "........oBBoooooBBo...............",
        ".......oBBBoo.oBBBoo..............",
        ".......obbbbboobbbbbo.............",
        "........ooooo..ooooo..............",
        ".................................."
      ],
      [
        "..........ooooooo.................",
        ".........ovvvvvvvo................",
        "........ovVVVVVVVvo...............",
        "..ovoo.ovvvvvvvvvvvo.ooVVo........",
        "..ovvvoovvvvbRRRRRbooVVVVo........",
        "..ovRvvvoBBBbbbbbbbVVVRVVo........",
        "..ovvRvvvBBBhhhhsooVVVRVVo........",
        "..ovvvRvvBBBhhhhhvoVVVVRVo........",
        "...oovvvvVVvvvvvvvvoVVVVVo........",
        "..oBBBBBvVVrrrrrVvvvVVVoo.........",
        "..oBBBBBVVVrRSRrbvvvVoooo.........",
        "..oBBBBBVVVrRRRrbvvBBBBBBooooooo..",
        "..oBBBBBVVVrRRRrbvBBBBBBvVVVVVVvo.",
        "..oBBBBBVVVrrrrrvvBBBBBBvvvvvvvvo.",
        "..oBBBBBvvvvvvvvvvbBBBBBvvvvvvvvo.",
        "..oBBBBBvhccccccchbBBBBBBooooooo..",
        "...ooooobhhhGGhhhhboooooo.........",
        "........oBBooooBBBo...............",
        "........oBBooooBBoo...............",
        "........obbbbbbbbbbo..............",
        ".........oooooooooo...............",
        ".................................."
      ],
      [
        "..........ooooooo.................",
        ".........ovvvvvvvo................",
        "........ovVVVVVVVvo...............",
        "..ovoo.ovvvvvvvvvvvo.ooVVo........",
        "..ovvvoovvvvbRRRRRbooVVVVo........",
        "..ovRvvvoBBBbbbbbbbVVVRVVo........",
        "..ovvRvvvBBBhhhhsooVVVRVVo........",
        "..ovvvRvvBBBhhhhhvoVVVVRVo........",
        "...oovvvvVVvvvvvvvvoVVVVVo........",
        "..oBBBBBvVVrrrrrVvvvVVVoo.........",
        "..oBBBBBVVVrRSRrbvvvVoooo.........",
        "..oBBBBBVVVrRRRrbvvBBBBBBooooooo..",
        "..oBBBBBVVVrRRRrbvBBBBBBvVVVVVVvo.",
        "..oBBBBBVVVrrrrrvvBBBBBBvvvvvvvvo.",
        "..oBBBBBvvvvvvvvvvbBBBBBvvvvvvvvo.",
        "..oBBBBBvhccccccchbBBBBBBooooooo..",
        "...ooooobhhhGGhhhhboooooo.........",
        "........oBBoooooBBo...............",
        ".......oBBBoo.oBBBoo..............",
        ".......obbbbboobbbbbo.............",
        "........ooooo..ooooo..............",
        ".................................."
      ]
    ]
  },
  "REACTOR_CORE": {
    "width": 26,
    "height": 27,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "w": "#c8e0c5",
      "S": "#f8d6a2",
      "G": "#f1ce7a",
      "c": "#74c9d0",
      "C": "#d0f2df",
      "r": "#a34549",
      "R": "#eb8060",
      "v": "#655170"
    },
    "frames": [
      [
        "..........................",
        ".......ooooooooooo........",
        "......oBBBBBBBBBBBo.......",
        ".....ooBwwwwwwwwwBoo......",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBoooooooooBBBo.....",
        "....oBBBvvvvvvvvvBBBo.....",
        "....ocBBvrrrrrrrvBBBo.....",
        "....ocBBvrRRRRRrvBBBo.....",
        "....ocBBvrRGGGRrvBBBo.....",
        "....ocBBvrRGSGRrvBBBo.....",
        "....ocBBvrRGGGRrvBBBo.....",
        "....ocBBvrRGGGRrvBBBo.....",
        "....oBBBvrRGGGRrvBBco.....",
        "....oBBBvrRGGGRrvBBco.....",
        "....oBBBvrRRRRRrvBBco.....",
        "....oBBBvrrrrrrrvBBco.....",
        "....oBBBvvvvvvvvvBBco.....",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        ".....oocccBBBBBcccoo......",
        "....obbBBBBBBBBBBBbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        ".....ooooooooooooooo......",
        ".........................."
      ],
      [
        "..........................",
        ".......ooooooooooo........",
        "......oBBBBBBBBBBBo.......",
        ".....ooBwwwwwwwwwBoo......",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBoooooooooBBBo.....",
        "....oBBBvvvvvvvvvBBBo.....",
        "....oCBBvrrrrrrrvBBBo.....",
        "....oCBBvrRRRRRrvBBBo.....",
        "....oCBBvrRGGGRrvBBBo.....",
        "....oCBBvrRGSGRrvBBBo.....",
        "....oCBBvrRGGGRrvBBBo.....",
        "....oCBBvrRGGGRrvBBBo.....",
        "....oBBBvrRGGGRrvBBCo.....",
        "....oBBBvrRGGGRrvBBCo.....",
        "....oBBBvrRRRRRrvBBCo.....",
        "....oBBBvrrrrrrrvBBCo.....",
        "....oBBBvvvvvvvvvBBCo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        ".....oocccBBBBBcccoo......",
        "....obbBBBBBBBBBBBbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        ".....ooooooooooooooo......",
        ".........................."
      ],
      [
        "..........................",
        ".......ooooooooooo........",
        "......oBBBBBBBBBBBo.......",
        ".....ooBwwwwwwwwwBoo......",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBoooooooooBBBo.....",
        "....oBBBvvvvvvvvvBBBo.....",
        "....owBBvrrrrrrrvBBBo.....",
        "....owBBvrRRRRRrvBBBo.....",
        "....owBBvrRGGGRrvBBBo.....",
        "....owBBvrRGSGRrvBBBo.....",
        "....owBBvrRGGGRrvBBBo.....",
        "....owBBvrRGGGRrvBBBo.....",
        "....oBBBvrRGGGRrvBBwo.....",
        "....oBBBvrRGGGRrvBBwo.....",
        "....oBBBvrRRRRRrvBBwo.....",
        "....oBBBvrrrrrrrvBBwo.....",
        "....oBBBvvvvvvvvvBBwo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        ".....oocccBBBBBcccoo......",
        "....obbBBBBBBBBBBBbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        ".....ooooooooooooooo......",
        ".........................."
      ],
      [
        "..........................",
        ".......ooooooooooo........",
        "......oBBBBBBBBBBBo.......",
        ".....ooBwwwwwwwwwBoo......",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBoooooooooBBBo.....",
        "....oBBBvvvvvvvvvBBBo.....",
        "....oCBBvrrrrrrrvBBBo.....",
        "....oCBBvrRRRRRrvBBBo.....",
        "....oCBBvrRGGGRrvBBBo.....",
        "....oCBBvrRGSGRrvBBBo.....",
        "....oCBBvrRGGGRrvBBBo.....",
        "....oCBBvrRGGGRrvBBBo.....",
        "....oBBBvrRGGGRrvBBCo.....",
        "....oBBBvrRGGGRrvBBCo.....",
        "....oBBBvrRRRRRrvBBCo.....",
        "....oBBBvrrrrrrrvBBCo.....",
        "....oBBBvvvvvvvvvBBCo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        "....oBBBBBBBBBBBBBBBo.....",
        ".....oocccBBBBBcccoo......",
        "....obbBBBBBBBBBBBbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        "....obbbbbbbbbbbbbbbo.....",
        ".....ooooooooooooooo......",
        ".........................."
      ]
    ]
  },
  "IRIS_COMMANDER": {
    "width": 16,
    "height": 22,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "t": "#344c65",
      "T": "#65819a",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "S": "#f8d6a2",
      "h": "#797c74",
      "H": "#c3c8ae",
      "g": "#b88f50",
      "G": "#e8cb7f",
      "c": "#74c9d0",
      "C": "#d0f2df"
    },
    "frames": [
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        ".gggGotto.......",
        "...ootTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....ob..bo......",
        "...obB..Bbo.....",
        "...ob....bo.....",
        "..ob......bo....",
        "..oo......oo....",
        ".ooo......ooo..."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        "....ootto.......",
        ".gggGtTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....obBBbo......",
        ".....obbo.......",
        ".....obBo.......",
        ".....oBbo.......",
        ".....obbo.......",
        ".....oooo......."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        ".gggGotto.......",
        "...ootTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....ob..bo......",
        "....oB..Bo......",
        ".....boob.......",
        "....ob..bo......",
        "...ob....bo.....",
        "...ooo...ooo...."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        "....ootto.......",
        ".gggGtTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....obBBbo......",
        ".....obbo.......",
        ".....obBo.......",
        ".....oBbo.......",
        ".....obbo.......",
        ".....oooo......."
      ]
    ]
  },
  "IRIS_ENGINEER": {
    "width": 16,
    "height": 22,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "t": "#8c4e33",
      "T": "#ce8b4b",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "S": "#f8d6a2",
      "h": "#543b39",
      "H": "#aa7351",
      "g": "#455f58",
      "G": "#77988a",
      "c": "#74c9d0",
      "C": "#d0f2df"
    },
    "frames": [
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        ".gggGotto.......",
        "...ootTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....ob..bo......",
        "...obB..Bbo.....",
        "...ob....bo.....",
        "..ob......bo....",
        "..oo......oo....",
        ".ooo......ooo..."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        "....ootto.......",
        ".gggGtTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....obBBbo......",
        ".....obbo.......",
        ".....obBo.......",
        ".....oBbo.......",
        ".....obbo.......",
        ".....oooo......."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        ".gggGotto.......",
        "...ootTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....ob..bo......",
        "....oB..Bo......",
        ".....boob.......",
        "....ob..bo......",
        "...ob....bo.....",
        "...ooo...ooo...."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        "....ootto.......",
        ".gggGtTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....obBBbo......",
        ".....obbo.......",
        ".....obBo.......",
        ".....oBbo.......",
        ".....obbo.......",
        ".....oooo......."
      ]
    ]
  },
  "VILLAGER": {
    "width": 16,
    "height": 22,
    "pixelScale": 0.5,
    "palette": {
      ".": "#000000",
      "o": "#14212c",
      "b": "#25394a",
      "B": "#476171",
      "t": "#4b6340",
      "T": "#91a765",
      "w": "#c8e0c5",
      "s": "#dba67d",
      "S": "#f8d6a2",
      "h": "#543b39",
      "H": "#aa7351",
      "g": "#856449",
      "G": "#c7a776",
      "c": "#74c9d0",
      "C": "#d0f2df"
    },
    "frames": [
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        ".gggGotto.......",
        "...ootTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....ob..bo......",
        "...obB..Bbo.....",
        "...ob....bo.....",
        "..ob......bo....",
        "..oo......oo....",
        ".ooo......ooo..."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        "....ootto.......",
        ".gggGtTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....obBBbo......",
        ".....obbo.......",
        ".....obBo.......",
        ".....oBbo.......",
        ".....obbo.......",
        ".....oooo......."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        ".gggGotto.......",
        "...ootTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....ob..bo......",
        "....oB..Bo......",
        ".....boob.......",
        "....ob..bo......",
        "...ob....bo.....",
        "...ooo...ooo...."
      ],
      [
        ".....oooooo.....",
        "....ohhhhhoo....",
        "...ohHHHhhhgo...",
        "...ohHHhhhgGGo..",
        "...ohSSSSoCCCo..",
        "...ohSsSSoccco..",
        "....osSSSoooo...",
        "....oSSSso......",
        "....ootto.......",
        ".gggGtTTtoo.....",
        "...otTTTTtgo....",
        "...otTTTwttgo...",
        "...otTTTTtgo....",
        "....otTTtoo.....",
        "....ogGGgo......",
        "....obBBbo......",
        "....obBBbo......",
        ".....obbo.......",
        ".....obBo.......",
        ".....oBbo.......",
        ".....obbo.......",
        ".....oooo......."
      ]
    ]
  }
};
