// Authored game content. Validated by content/compile.js.
export default {
  "version": 2,
  "id": "wayfarer",
  "name": "The trailkeeper",
  "width": 16,
  "height": 22,
  "pixelScale": 0.5,
  "palette": {
    ".": "#000000",
    "o": "#14212c",
    "b": "#243747",
    "B": "#476171",
    "t": "#28636b",
    "T": "#61a49a",
    "w": "#c8e0c5",
    "s": "#dba67d",
    "S": "#f8d6a2",
    "h": "#543b39",
    "H": "#a56c4d",
    "g": "#b4553d",
    "G": "#ef9d59",
    "p": "#38564f"
  },
  "limbs": {
    "outline": "o",
    "sleeve": "T",
    "skin": "s",
    "hand": "S"
  },
  "clips": {
    "idle": {
      "ticks": 32,
      "frames": [
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "...ooogGGGgoo...",
          "..oppoGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obBBBo.....",
          ".....obB.Bbo....",
          ".....obB.Bbo....",
          ".....ob..Bbo....",
          "....ohHo.hHho...",
          "....oooo.oooo..."
        ],
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obBBBo.....",
          ".....obB.Bbo....",
          ".....obB.Bbo....",
          ".....ob..Bbo....",
          "....ohHo.hHho...",
          "....oooo.oooo..."
        ]
      ]
    },
    "walk": {
      "ticks": 7,
      "frames": [
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          "....obB.Bbo.....",
          "...obB..Bbo.....",
          "...ob...Bbo.....",
          "..ob....Bbo.....",
          "..ohHo..hHho....",
          "..oooo..oooo...."
        ],
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "...ooogGGGgoo...",
          "..oppoGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obBBBo.....",
          ".....obBBbo.....",
          "......obBbo.....",
          "......obBbo.....",
          ".....ohHHho.....",
          ".....oooooo....."
        ],
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obB.Bbo....",
          ".....obB..Bbo...",
          ".....obB...bo...",
          ".....obB....bo..",
          "....ohHo...hHho.",
          "....oooo...oooo."
        ],
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "...ooogGGGgoo...",
          "..oppoGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obBBBo.....",
          ".....obB.Bbo....",
          ".....obB.Bbo....",
          ".....ob..Bbo....",
          "....ohHo.hHho...",
          "....oooo.oooo..."
        ]
      ]
    },
    "run": {
      "ticks": 5,
      "frames": [
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          "....obB.Bbo.....",
          "...obB...Bbo....",
          "..obB....Bbo....",
          "..oB.....hHho...",
          ".ohHo....oooo...",
          ".oooo..........."
        ],
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obB.Bbo....",
          "......ob.Bbo....",
          ".......obBbo....",
          ".......obBbo....",
          "......ohHHho....",
          "......oooooo...."
        ],
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obB.Bbo....",
          ".....obB..Bbo...",
          ".....obB...bo...",
          ".....obB....bo..",
          "....ohHo...hHho.",
          "....oooo...oooo."
        ],
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "...ooogGGGgoo...",
          "..oppoGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obBBBo.....",
          ".....obBBbo.....",
          "......obBbo.....",
          "......obBbo.....",
          ".....ohHHho.....",
          ".....oooooo....."
        ]
      ]
    },
    "rise": {
      "ticks": 9,
      "frames": [
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          "....obB.Bbo.....",
          "...obB..Bbo.....",
          "...ohHo.Bbo.....",
          "...oooo.Bbo.....",
          ".......ohHho....",
          ".......oooo....."
        ]
      ]
    },
    "fall": {
      "ticks": 9,
      "frames": [
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obB.Bbo....",
          ".....obB.Bbo....",
          "....obB...Bbo...",
          "....ob....Bbo...",
          "...ohHo...hHho..",
          "...oooo...oooo.."
        ]
      ]
    },
    "wade": {
      "ticks": 11,
      "frames": [
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          "....obB.Bbo.....",
          "...obB..Bbo.....",
          "...ob...Bbo.....",
          "..ob....Bbo.....",
          "..ohHo..hHho....",
          "..oooo..oooo...."
        ],
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obB.Bbo....",
          ".....obB..Bbo...",
          ".....obB...bo...",
          ".....obB....bo..",
          "....ohHo...hHho.",
          "....oooo...oooo."
        ]
      ]
    },
    "swim": {
      "ticks": 9,
      "frames": [
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          "....obB.BBbo....",
          "...obB...Bbo....",
          "..ohHo...hHho...",
          "..oooo...oooo...",
          "................",
          "................"
        ],
        [
          ".....oooooo.....",
          "....ohHHHHho....",
          "....oHHHHHHho...",
          "....ohhSSSSSo...",
          ".....osSSoSoo...",
          ".....osSSSSSo...",
          "......osSSoo....",
          "..gggogGGGgoo...",
          ".g...oGggggoo...",
          "..oppotTTTto....",
          "..oppotTwTtso...",
          "...ppoTTTTtso...",
          "....otTTTTtoo...",
          "....otTTTtoo....",
          ".....ogGggo.....",
          ".....obBBBo.....",
          ".....obB.Bbo....",
          ".....obB..Bbo...",
          "....ohHo...hHho.",
          "....oooo...oooo.",
          "................",
          "................"
        ]
      ]
    }
  }
};
