import assert from 'node:assert/strict';
import { encodeAdventureOrigin, decodeAdventureOrigin } from '../src/sand/worker/adventureSaveStore.js';
import { normalizeReplayInit } from '../src/sand/game/replayCapsule.js';
import { initSandWasm, createEngineWasm, PLANET, MAT } from '../src/sand/wasmBridge/engineFactory.js';
import { MISSION, ITEM_KIND } from '../src/sand/wasmBridge/abi.generated.js';
import { GAME_WORLD } from '../src/sand/content/catalog.js';
await initSandWasm();
const options = { cols:640, rows:448, worldSeed:GAME_WORLD.seed, infinite:true, sinksOn:false, planetId:PLANET.FRONTIER };
const e = createEngineWasm(options);
const fresh = [];
try {
  e.setSurvivalInventory(true); e.setCreatureRuntime(false,false);
  const id = e.spawnPlayerAtSurface(320); e.startMission(MISSION.FRONTIER,id);
  const move = (wx,wy) => e.setPlayerState(id,{...e.getPlayer(id),x:wx-e.getWorldOffsetX(),y:wy-e.getWorldOffsetY(),vx:0,vy:0});
  const step = (n=12) => { for(let i=0;i<n;i++) e.stepActors(); };
  let inventory = e.getInventory(id);
  assert.equal(inventory.slots.length,36); assert.equal(inventory.equipment.length,9);
  assert.equal(inventory.slots[0].itemKind,ITEM_KIND.GEAR);
  assert.equal(inventory.slots[0].definitionId,1);
  assert.equal(inventory.equipment[0].definitionId,100);
  e.inventoryCursorPick(id,0,false);
  const cursor = e.getCursor(id); e.inventoryCursorPick(id,36,false);
  assert.deepEqual(e.getCursor(id),cursor,'sword cannot replace a hood');
  e.inventoryCursorPick(id,0,false);
  assert.ok(e.addGear(id,106));
  const hoodSlot = e.getInventory(id).slots.findIndex(s=>s.definitionId===106);
  e.inventoryCursorPick(id,hoodSlot,false); e.inventoryCursorPick(id,36,false);
  assert.equal(e.getInventory(id).equipment[0].definitionId,106);
  assert.equal(e.getCursor(id).definitionId,100,'equipment swaps preserve the previous piece');
  e.inventoryCursorPick(id,hoodSlot,false);
  assert.equal(e.interactFrontier(id,0),false,'quest cannot be accepted at a distance');
  const osei = e.getCreatures().find(n=>n.npcId===2);
  assert.ok(osei,'named NPC identity is replicated');
  move(osei.x+e.getWorldOffsetX(),osei.y+e.getWorldOffsetY());
  assert.ok(e.interactFrontier(id,0)); assert.ok(e.getMission().objectives[0].accepted);
  e.addToInventory(id,MAT.IRON_ORE,31); step();
  assert.ok(e.interactFrontier(id,0));
  assert.equal(e.getMission().objectives[0].state,2);
  const allOre = e.getInventory(id).pools.flatMap(p=>p.entries).find(s=>s.material===MAT.IRON_ORE)?.count;
  assert.equal(allOre,7,'handoff consumes only the requested material');
  assert.equal(e.interactFrontier(id,0),false,'completed quest cannot pay twice');
  console.log('ok: equipment swaps and NPC handoff');
  const chest=e.getChests().find(c=>c.id===1);
  assert.equal(e.interactChest(id,1),false,'a chest must be within reach');
  move(chest.worldX,chest.worldY-2); assert.ok(e.interactChest(id,1));
  const loot=e.getChestLoot().slots.length;
  assert.ok(e.interactChest(id,1,0)); assert.equal(e.getChestLoot().slots.length,loot-1);
  console.log('ok: chest transfers');
  e.eraseDiscLayer(0,90,90,5);e.eraseDiscLayer(1,90,90,5);
  e.paintDisc(150,90,4,MAT.WATER,true);
  e.spawnBody(Array.from({length:12},(_,i)=>[420+i%4,60+Math.floor(i/4)]));
  console.log('fixture: body and water placed');
  e.stepWorld(); step();
  console.log('fixture: world stepped');
  const fg=e.getGrid().slice(),bg=e.getGridBg().slice();
  const saved=e.writeCheckpoint(); assert.ok(saved.length>1000);
  console.log('ok: checkpoint written');
  const restored=createEngineWasm(options); fresh.push(restored);
  assert.ok(restored.readCheckpoint(saved));
  assert.deepEqual(restored.getGrid(),fg,'foreground is restored exactly');
  assert.deepEqual(restored.getGridBg(),bg,'background is restored exactly');
  assert.deepEqual(restored.getInventory(id),e.getInventory(id),'gear and pooled materials survive reload');
  assert.deepEqual(restored.getChests(),e.getChests(),'chest contents are not regenerated');
  assert.deepEqual(restored.getMission().objectives,e.getMission().objectives,'quest acceptance and completion persist');
  console.log('ok: checkpoint exact state round-trip');
  const origin=await encodeAdventureOrigin(saved);
  const replayInit=normalizeReplayInit({...options,checkpoint:origin});
  assert.deepEqual((await decodeAdventureOrigin(replayInit.checkpoint)).bytes,saved,'resumed-world replay origins preserve the complete checkpoint');
  for(let i=0;i<12;i++){restored.stepWorld();restored.stepActors();}
  assert.ok(restored.getPlayer(id).alive,'restored components and moving bodies remain simulatable');
  const broken=saved.slice();broken[broken.length>>1]^=128;
  const invalid=createEngineWasm(options);fresh.push(invalid);
  const before=invalid.getGrid().slice();
  assert.equal(invalid.readCheckpoint(broken),false);
  assert.deepEqual(invalid.getGrid(),before,'checksum validation precedes mutation');
  console.log('ok: authoritative gear, NPC handoff, loot transactions, full checkpoint and damaged-world resume');
} finally {e.destroy();for(const engine of fresh)engine.destroy();}
