import { runBrowserCases } from './browser-harness.mjs';
import { mkdirSync } from 'node:fs';
import process from 'node:process';
const artifacts='.sand-artifacts/adventure-browser';mkdirSync(artifacts,{recursive:true});
process.exitCode=await runBrowserCases({adventure:async({page,baseURL,check})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(baseURL+'/game',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>document.querySelector('sand-game')?._game?.getPlayer(),null,{timeout:60000});
 const initialDay=await page.evaluate(()=>document.querySelector('sand-game')._game.getDayNight());
 await page.waitForFunction(phase=>document.querySelector('sand-game')._game.getDayNight().phase>phase+.0005,initialDay.phase);
 check('survival daylight advances automatically',!initialDay.overridden);
 await page.waitForFunction(()=>document.querySelector('sand-game')._game.getBeds().length>=3);
 check('resident beds are replicated from the authority',true);
 await page.evaluate(()=>document.fonts.load('16px "Sand Pixel"'));
 await page.getByRole('button',{name:'Journal (J)',exact:true}).waitFor();
 check('starts directly in the world',await page.getByRole('button',{name:'Start exploring'}).count()===0);
 await page.keyboard.press('j');await page.getByRole('dialog',{name:'Journal',exact:true}).waitFor();
 check('one main panel',await page.locator('[role=dialog]:visible').count()===1);
 await page.screenshot({path:artifacts+'/journal.png'});
 await page.getByRole('button',{name:'Inventory',exact:true}).click();
 await page.getByRole('button',{name:'Head: Wayfarer hood',exact:true}).waitFor();
 await page.getByRole('button',{name:'Head: Wayfarer hood',exact:true}).click();
 await page.getByRole('button',{name:'Head: Unequipped',exact:true}).waitFor();
 check('equipment updates while gameplay rests',true);
 await page.getByRole('button',{name:'Head: Unequipped',exact:true}).click();
 await page.getByRole('button',{name:'Head: Wayfarer hood',exact:true}).waitFor();
 await page.screenshot({path:artifacts+'/inventory.png'});
 await page.getByRole('button',{name:'Map',exact:true}).click();
 await page.screenshot({path:artifacts+'/map.png'});
 await page.keyboard.press('Escape');
 await page.locator('sand-game').evaluate(host=>host.shadowRoot.querySelector('.sg-sim').focus());
 const initial=await page.evaluate(()=>document.querySelector('sand-game')._game.getPlayer().x);
 await page.keyboard.down('d');await page.waitForTimeout(550);await page.keyboard.up('d');
 check('ordinary movement works after closing a panel',await page.evaluate(x=>document.querySelector('sand-game')._game.getPlayer().x>x+1,initial));
 for(let i=0;i<50;i++){
  const dx=await page.evaluate(()=>{const g=document.querySelector('sand-game')._game,v=g.getMissionView(),c=g.getChests()[0];return c.worldX-v.playerWorldX;});
  if(Math.abs(dx)<18)break;
  const key=dx<0?'a':'d';await page.keyboard.down(key);await page.waitForTimeout(90);await page.keyboard.up(key);
 }
 await page.waitForTimeout(400);
 await page.mouse.move(2,2);await page.keyboard.press('e');
 await page.getByRole('dialog',{name:'Inventory',exact:true}).waitFor();
 check('proximity alone does not open a chest',await page.getByRole('button',{name:'Take all',exact:true}).count()===0);
 await page.keyboard.press('Escape');
 const chestPoint=await page.evaluate(()=>{const host=document.querySelector('sand-game'),g=host._game,c=g.getChests()[0],r=window.__sandTest.cellRect(c.worldX-window.__sandTest.worldOffset().x,c.worldY+2-window.__sandTest.worldOffset().y),bounds=host.shadowRoot.querySelector('#sand-main').getBoundingClientRect();return {x:bounds.x+r.x/devicePixelRatio,y:bounds.y+r.y/devicePixelRatio};});
 await page.mouse.move(chestPoint.x,chestPoint.y);
 await page.locator('.ad-chest-prompt').waitFor({state:'visible'});
 check('hover highlights the chest itself',await page.locator('.ad-chest-highlight').isVisible());
 await page.screenshot({path:artifacts+'/chest-hover.png'});
 await page.getByRole('button',{name:'Open chest (E)',exact:true}).click();
 await page.getByRole('button',{name:'Take all',exact:true}).waitFor();
 await page.keyboard.press('Escape');
 await page.mouse.move(2,2);
 check('chest prompt clears when the pointer leaves',!(await page.locator('.ad-chest-prompt').isVisible()));
 await page.mouse.move(chestPoint.x,chestPoint.y);await page.keyboard.press('e');
 await page.getByRole('button',{name:'Take all',exact:true}).waitFor();
 await page.screenshot({path:artifacts+'/chest.png'});
 await page.getByRole('button',{name:'Take all',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('sand-game')._game.getChestLoot().slots.every(s=>!s.count));
 check('empty chests retain 24 usable slots',await page.locator('[data-chest-slot]').count()===24);
 const source=await page.evaluate(()=>document.querySelector('sand-game')._game.getInventory().slots.findIndex(s=>s.definitionId===1&&s.count>0));
 await page.locator(`.inv-hud [data-index="${source}"]`).click();
 await page.waitForFunction(()=>document.querySelector('sand-game')._game.getCursor()?.count>0);
 await page.locator('[data-chest-slot="23"]').click();
 await page.waitForFunction(()=>document.querySelector('sand-game')._game.getChestLoot().slots[23].count>0);
 check('a carried item can be put in an empty chest slot',await page.evaluate(()=>!document.querySelector('sand-game')._game.getCursor()));
 await page.locator('[data-chest-slot="23"]').click();
 await page.waitForFunction(()=>document.querySelector('sand-game')._game.getCursor()?.count>0);
 await page.locator(`.inv-hud [data-index="${source}"]`).click();
 await page.waitForFunction(()=>!document.querySelector('sand-game')._game.getCursor());
 const lootedAt=await page.evaluate(()=>{const time=Date.now();window.dispatchEvent(new Event('pagehide'));return time;});
 await page.waitForFunction(time=>document.querySelector('sand-game')._game.getSaveState().savedAt>=time,lootedAt,{timeout:30000});
 const saved=await page.evaluate(()=>document.querySelector('sand-game')._game.getInventory());
 await page.reload({waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>{const g=document.querySelector('sand-game')?._game;return g?.getSaveState().restored && window.__sandPerf().mirrorWorldTick > 0 && g.getInventory()?.equipment?.length && g.getChests().length;},null,{timeout:60000});
 await page.waitForFunction(()=>document.querySelector('sand-game')._game.getChests()[0]?.remaining===0,null,{timeout:10000});
 check('reload restores looted chest',true);
 check('reload restores equipment',await page.evaluate(ids=>JSON.stringify(document.querySelector('sand-game')._game.getInventory().equipment.map(s=>s.definitionId))===JSON.stringify(ids),saved.equipment.map(s=>s.definitionId)));
 for(const size of [{width:900,height:650},{width:390,height:844}]){
  await page.setViewportSize(size);await page.getByRole('button',{name:'Inventory (I)',exact:true}).click();
  check(`inventory fits ${size.width}px`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:'Close panel',exact:true}).click();
 }
 await page.getByRole('button',{name:'Inventory (I)',exact:true}).click();
 await page.waitForTimeout(1000);
 const recovered = await page.evaluate(async()=>{
  const {loadAdventure,saveAdventure}=await import('/src/sand/worker/adventureSaveStore.js');
  const good=await loadAdventure();await saveAdventure(good.bytes);await saveAdventure(good.bytes);
  const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('aster-adventures',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
  await new Promise((resolve,reject)=>{
   const tx=db.transaction('checkpoints','readwrite'),store=tx.objectStore('checkpoints'),keys=store.getAllKeys();
   keys.onsuccess=()=>{for(const key of keys.result)if(!key.endsWith(':previous'))store.put({bytes:new Uint8Array(32),compressed:false},key);};
   tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);
  });db.close();
  const restored=await loadAdventure(),again=await loadAdventure();
  return restored.bytes.length===good.bytes.length&&restored.bytes.every((v,i)=>v===good.bytes[i])&&again.bytes.every((v,i)=>v===good.bytes[i]);
 });
 check('a corrupt latest checkpoint recovers and repairs from the previous save',recovered);
 await page.getByRole('button',{name:'Journal',exact:true}).click();
 await page.getByText('Settings & controls',{exact:true}).click();
 await page.getByRole('button',{name:'Start fresh…',exact:true}).click();
 await page.screenshot({path:artifacts+'/restart-mobile.png'});
 check('restart confirmation fits on mobile',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByRole('button',{name:'Keep playing',exact:true}).click();
 check('cancelling keeps the current adventure',await page.evaluate(()=>document.querySelector('sand-game')._game.getChests()[0]?.remaining===0));
 await page.evaluate(()=>{
  const g=document.querySelector('sand-game')._game;
  window.restartAdventure=g.deleteAdventureSave;
  g.deleteAdventureSave=()=>Promise.reject(new Error('Storage is temporarily unavailable.'));
 });
 await page.getByRole('button',{name:'Start fresh…',exact:true}).click();
 await page.getByRole('button',{name:'Delete save & restart',exact:true}).click();
 await page.getByText('Storage is temporarily unavailable.',{exact:true}).waitFor();
 check('failed deletion leaves the confirmation usable',await page.getByRole('button',{name:'Keep playing',exact:true}).isEnabled());
 await page.evaluate(async()=>{
  const g=document.querySelector('sand-game')._game;
  g.setAudioMuted(true);localStorage.setItem('restart-unrelated','keep');
  const {GAME_WORLD,GAME_JOBS}=await import('/src/sand/content/catalog.js');
  localStorage.setItem(`aster-journal:3:${GAME_WORLD.seed}`,JSON.stringify({tracked:GAME_JOBS[0].key,seen:[]}));
  const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('aster-adventures',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
  // Hold the checkpoint store while the worker starts a save, then release it during deletion.
  const tx=db.transaction('checkpoints','readwrite'),store=tx.objectStore('checkpoints');
  let release=false;setTimeout(()=>{release=true;},1500);
  const hold=()=>{const r=store.count();r.onsuccess=()=>{if(!release)hold();};};hold();
  tx.oncomplete=()=>db.close();
  window.dispatchEvent(new Event('pagehide'));
  g.deleteAdventureSave=async()=>{
   await window.restartAdventure();
   window.dispatchEvent(new Event('pagehide'));
   await new Promise(resolve=>setTimeout(resolve,250));
   const cleanDb=await new Promise(resolve=>{const r=indexedDB.open('aster-adventures',1);r.onsuccess=()=>resolve(r.result);});
   const count=await new Promise(resolve=>{const r=cleanDb.transaction('checkpoints').objectStore('checkpoints').count();r.onsuccess=()=>resolve(r.result);});
   cleanDb.close();sessionStorage.setItem('restart-record-count',String(count));
  };
 });
 await page.waitForTimeout(250);
 await page.getByRole('button',{name:'Delete save & restart',exact:true}).click();
 await page.waitForFunction(()=>sessionStorage.getItem('restart-record-count')==='0',null,{timeout:30000});
 await page.waitForFunction(()=>{const g=document.querySelector('sand-game')?._game;return g?.getPlayer()&&g.getChests()[0]?.remaining>0;},null,{timeout:60000});
 check('restart clears current and backup saves despite pending and pagehide saves',await page.evaluate(()=>sessionStorage.getItem('restart-record-count')==='0'));
 check('restart creates a fresh adventure',await page.evaluate(()=>!document.querySelector('sand-game')._game.getSaveState().restored));
 check('restart preserves sound preferences and unrelated storage',await page.evaluate(()=>document.querySelector('sand-game')._game.getAudioState().muted&&localStorage.getItem('restart-unrelated')==='keep'));
 check('restart clears journal tracking',await page.evaluate(()=>document.querySelector('sand-game').dataset.trackedObjective==='-1'));
 check('no browser errors',errors.length===0,errors.join('; '));
},'resident-bed-render':async({page,baseURL,check})=>{
 await page.goto(baseURL+'/bed-art-fixture');
 const result=await page.evaluate(async()=>{
  const {initSandWasm,createEngineWasm,PLANET}=await import('/src/sand/wasmBridge/engineFactory.js');
  const {MISSION}=await import('/src/sand/wasmBridge/abi.generated.js');
  const {GAME_WORLD}=await import('/src/sand/content/catalog.js');await initSandWasm();
  const e=createEngineWasm({cols:640,rows:448,worldSeed:GAME_WORLD.seed,infinite:true,sinksOn:false,planetId:PLANET.FRONTIER});
  e.setSurvivalInventory(true);e.setCreatureRuntime(true,false);
  const player=e.spawnPlayerAtSurface(320);e.startMission(MISSION.FRONTIER,player);
  e.setDayPhase(.9);for(let i=0;i<1100;i++)e.stepActors();
  const beds=e.getBeds(),bed=beds.find(b=>b.sleeper);
  const canvas=document.createElement('canvas');canvas.width=960;canvas.height=480;document.body.replaceChildren(canvas);
  e.glInit(canvas);e.glResize(960,480);e.setViewport(1,8,120,60);
  e.cameraSet(bed.worldX-e.getWorldOffsetX()-60,bed.worldY-e.getWorldOffsetY()-35);
  e.glSetFlags(false,false,true);e.setSkyLight(130);e.glSetBeds(beds);e.glRenderFrame(true);
  const furnished=e.glReadPixels(424,260,112,60);
  e.glSetBeds([]);e.glRenderFrame(false);const bare=e.glReadPixels(424,260,112,60);
  let changed=0;for(let i=0;i<bare.length;i+=4)if(furnished[i]!==bare[i]||furnished[i+1]!==bare[i+1]||furnished[i+2]!==bare[i+2])changed++;
  e.glSetBeds(beds);e.glRenderFrame(false);
  window.bedRenderEngine=e;
  return {sleepers:beds.filter(b=>b.sleeper).length,changed};
 });
 check('sleeping residents and beds render in the generated village',result.sleepers>=3&&result.changed>100);
 await page.screenshot({path:artifacts+'/sleeping-residents.png'});
 await page.evaluate(()=>window.bedRenderEngine.destroy());
}});
