// Code generator for the shared JS<->WASM ABI manifest.
//
//   node scripts/generate-abi.mjs           # regenerate
//   node scripts/generate-abi.mjs --check   # fail if outputs are stale
//
// Reads src/sand/abi.schema.json (the single source of truth for packed
// snapshot layouts, shared enums, and the ABI version) and emits:
//   src/sand/cpp/engine/abi.generated.hpp   (stride constants + field-offset enums)
//   src/sand/wasmBridge/abi.generated.js    (same, plus named enum objects)
// Both are committed. C++ snapshot builders write fields by named offset and
// JS reads them by the same names, so a layout change is one schema edit + a
// version bump — never a silent positional shift.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const schemaPath = resolve(root, 'src/sand/abi.schema.json');
const hppPath = resolve(root, 'src/sand/cpp/engine/abi.generated.hpp');
const jsPath = resolve(root, 'src/sand/wasmBridge/abi.generated.js');

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
const { abiVersion, structs, enums, constants } = schema;
if (!Number.isInteger(abiVersion) || abiVersion < 1) throw new Error('abiVersion must be a positive integer');

const header = (comment) => `// GENERATED by scripts/generate-abi.mjs from src/sand/abi.schema.json — DO NOT EDIT.\n// ${comment}\n`;

// ---------------- C++ ----------------
let hpp = header('Strides + field offsets for the packed JS<->WASM snapshots, shared enums, and the ABI version.');
hpp += '#pragma once\n#include <cstdint>\n\n';
hpp += `static const int ABI_VERSION = ${abiVersion};\n\n`;
for (const [name, s] of Object.entries(structs)) {
  const fields = s.fields;
  const strideName = `${s.cPrefix}_STRIDE`;
  hpp += `// ${name}: ${fields.join(', ')}\n`;
  hpp += `enum ${name.charAt(0).toUpperCase() + name.slice(1)}Field : int {\n`;
  hpp += fields.map((f, i) => `  ${s.cPrefix}_${f.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()} = ${i},`).join('\n');
  hpp += `\n};\nstatic const int ${strideName} = ${fields.length};\n\n`;
}
for (const [name, e] of Object.entries(enums)) {
  hpp += `enum ${e.cName} : ${e.cType || 'int'} {\n`;
  hpp += Object.entries(e.values).map(([k, v]) => `  ${k} = ${v},`).join('\n');
  hpp += '\n};\n\n';
}
for (const [k, v] of Object.entries(constants)) {
  if (k.startsWith('$')) continue;
  hpp += `static const int ${k} = ${v};\n`;
}

// ---------------- JS ----------------
const jsIdent = (f) => f;
let js = header('Mirrors abi.generated.hpp: strides, named field offsets, shared enums, ABI version.');
js += `export const ABI_VERSION = ${abiVersion};\n\n`;
js += 'export const STRIDES = Object.freeze({\n';
js += Object.entries(structs).map(([name, s]) => `  ${name}: ${s.fields.length},`).join('\n');
js += '\n});\n\n';
js += '// Field offset maps: OFF.<struct>.<field> is the float/int index within one record.\n';
js += 'export const OFF = Object.freeze({\n';
for (const [name, s] of Object.entries(structs)) {
  js += `  ${name}: Object.freeze({ ${s.fields.map((f, i) => `${jsIdent(f)}: ${i}`).join(', ')} }),\n`;
}
js += '});\n\n';
for (const [name, e] of Object.entries(enums)) {
  const strip = (k) => k.replace(/^(PI|T|CK)_/, '');
  js += `export const ${name === 'PlayerInput' ? 'INPUT' : name === 'Tool' ? 'TOOL' : 'CREATIVE_KIND'} = Object.freeze({ ${Object.entries(e.values).map(([k, v]) => `${strip(k)}: ${v}`).join(', ')} });\n`;
}
js += '\n';
for (const [k, v] of Object.entries(constants)) {
  if (k.startsWith('$')) continue;
  js += `export const ${k} = ${v};\n`;
}

// ---------------- emit / check ----------------
const check = process.argv.includes('--check');
const outputs = [[hppPath, hpp], [jsPath, js]];
let stale = false;
for (const [path, content] of outputs) {
  if (check) {
    let cur = '';
    try { cur = readFileSync(path, 'utf8'); } catch { /* missing */ }
    if (cur !== content) { stale = true; console.error(`stale: ${path}`); }
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}
if (check && stale) { console.error('Generated ABI files are stale. Run `npm run generate:abi`.'); process.exit(1); }
if (check) console.log('generated ABI files are up to date');
