// Unity translation unit for the C++/WASM sand engine. Engine owns shared state
// and cross-system coordination; composed subsystem classes hold gameplay policy.

#include "engine/common.hpp"
#include "engine/camera.hpp"
#include "engine/replication.hpp"
#include "engine/layer.hpp"
#include "engine/forces.hpp"
#include "engine/terrain.hpp"
#include "engine/weather.hpp"
#include "engine/world_context.hpp"
#include "engine/renderer.hpp"
#include "engine/creatures.hpp"
#include "engine/checkpoint.hpp"
#include "engine/containers.hpp"
#include "engine/content.hpp"
#include "engine/combat.hpp"
#include "engine/discovery.hpp"
#include "engine/missions.hpp"
#include "engine/glpresenter.hpp"
#include "engine/items.hpp"
#include "engine/inventory.hpp"
#include "engine/crafting.hpp"
#include "engine/projectiles.hpp"
#include "engine/player.hpp"
#include "engine/tools.hpp"
#include "engine/reactions.hpp"
#include "engine/reaction_transaction.hpp"
#include "engine/explosives.hpp"
#include "engine/growth.hpp"
#include "engine/components.hpp"
#include "engine/cell_mutations.hpp"
#include "engine/rigid.hpp"
#include "engine/audio.hpp"

struct Engine {
  ContentSystem content{*this};
  DiscoverySystem discovery{*this};
  CombatSystem combat{*this};
  ContainerSystem containers{*this};
  CheckpointSystem checkpoint{*this};
#include "engine/members.inc"
#include "engine/forces.inc"
#include "engine/weather.inc"
#include "engine/audio.inc"
#include "engine/core.inc"
#include "engine/step.inc"
#include "engine/components.inc"
#include "engine/reactions.inc"
#include "engine/growth.inc"
#include "engine/tools.inc"
#include "engine/worldgen.inc"
#include "engine/world_context.inc"
#include "engine/rigid.inc"
#include "engine/explosives.inc"
#include "engine/render.inc"
#include "engine/camera.inc"
#include "engine/gl.inc"
#include "engine/player.inc"
#include "engine/items.inc"
#include "engine/creatures.inc"
#include "engine/missions.inc"
#include "engine/inventory.inc"
#include "engine/crafting.inc"
#include "engine/projectiles.inc"
#include "engine/replication.inc"
};

// Out-of-line definitions of the Engine static constants.
const int Engine::DIRS_LF[2] = {-1, 1};
const int Engine::DIRS_RF[2] = {1, -1};

// Subsystem method bodies require the complete Engine definition.
#include "engine/content_impl.inc"
#include "engine/combat_impl.inc"
#include "engine/containers_impl.inc"
#include "engine/checkpoint_impl.inc"
#include "engine/discovery_impl.inc"
#include "engine/replication_impl.inc"
#include "engine/forces_impl.inc"
#include "engine/terrain_impl.inc"
#include "engine/world_context_impl.inc"
#include "engine/renderer_impl.inc"
#include "engine/glpresenter_impl.inc"
#include "engine/items_impl.inc"
#include "engine/inventory_impl.inc"
#include "engine/crafting_impl.inc"
#include "engine/projectiles_impl.inc"
#include "engine/player_impl.inc"
#include "engine/creatures_impl.inc"
#include "engine/missions_impl.inc"
#include "engine/tools_impl.inc"
#include "engine/cell_mutations_impl.inc"
#include "engine/weather_impl.inc"
#include "engine/reaction_transaction_impl.inc"
#include "engine/reactions_impl.inc"
#include "engine/explosives_impl.inc"
#include "engine/growth_impl.inc"
#include "engine/components_impl.inc"
#include "engine/rigid_impl.inc"
#include "engine/audio_impl.inc"

#include "engine/abi.inc"
